# utils.py
# ============================================================
# Shared utility functions used across multiple flow modules.
# Import from here instead of defining locally in each file.
# ============================================================

import uuid
import time
import re
import os
import json
from datetime import datetime, date, timedelta
from dotenv import load_dotenv
from config import USER_STATE

load_dotenv()

# Initialize Groq client
from llm_config import groq_client as _client, MODEL_NAME as _MODEL_NAME, smart_llm_call

# ============================================================
# TOKEN MANAGEMENT
# ============================================================

# In-memory token store for upload tokens generated via app.py endpoints.
# Tokens generated by insurance.py are stored inside USER_STATE[phone]["upload_token"].
UPLOAD_TOKENS: dict = {}

TOKEN_EXPIRY_SECONDS = 3600  # 1 hour


def generate_upload_token(phone: str, name: str, vehicle: str) -> str:
    """
    Generate a secure UUID-based upload token and persist it in USER_STATE
    so it can be validated later by get_user_from_token().

    Stores the token under USER_STATE[phone]["upload_token"] which is the
    single source of truth checked by get_user_from_token().
    """
    token = str(uuid.uuid4())

    USER_STATE.setdefault(phone, {})
    USER_STATE[phone]["upload_token"] = {
        "token": token,
        "name": name,
        "vehicle": vehicle,
        "timestamp": time.time(),
        "mobile": phone,   # kept for convenience when retrieved via token scan
    }

    print(f"✅ Generated upload token for {phone}: {token}")
    return token


def get_user_from_token(token: str) -> dict | None:
    """
    Validate a token and return the associated user data dict, or None if the
    token is missing / expired.

    Checks USER_STATE first (tokens created by insurance flow / generate_upload_token),
    then falls back to the legacy UPLOAD_TOKENS dict kept for backward compatibility.

    Returned dict keys: mobile, name, vehicle, timestamp
    """
    # ── 1. Scan USER_STATE (primary store) ──────────────────────────────
    for phone, user_data in USER_STATE.items():
        token_data = user_data.get("upload_token")
        if not token_data:
            continue
        if token_data.get("token") != token:
            continue

        if time.time() - token_data.get("timestamp", 0) > TOKEN_EXPIRY_SECONDS:
            print(f"❌ Token expired in USER_STATE: {token}")
            user_data.pop("upload_token", None)
            return None

        print(f"✅ Valid token from USER_STATE for {phone}")
        return {
            "mobile": phone,
            "name": token_data.get("name", ""),
            "vehicle": token_data.get("vehicle", ""),
            "timestamp": token_data.get("timestamp", 0),
        }

    # ── 2. Fallback: legacy UPLOAD_TOKENS dict ───────────────────────────
    if token in UPLOAD_TOKENS:
        data = UPLOAD_TOKENS[token]
        if time.time() - data.get("timestamp", 0) > TOKEN_EXPIRY_SECONDS:
            print(f"❌ Token expired in UPLOAD_TOKENS: {token}")
            UPLOAD_TOKENS.pop(token, None)
            return None

        print(f"✅ Valid token from UPLOAD_TOKENS for {data['mobile']}")
        return data

    print(f"❌ Token not found: {token}")
    return None


def revoke_upload_token(token: str) -> None:
    """Remove a token from both USER_STATE and UPLOAD_TOKENS after successful upload."""
    # Remove from legacy dict
    UPLOAD_TOKENS.pop(token, None)

    # Remove from USER_STATE
    for phone, user_data in USER_STATE.items():
        token_data = user_data.get("upload_token")
        if token_data and token_data.get("token") == token:
            user_data.pop("upload_token", None)
            print(f"✅ Token revoked from USER_STATE for {phone}")
            break


# ============================================================
# PHONE NUMBER FORMATTING
# ============================================================

def format_mobile(phone: str) -> str:
    """
    Format an Indian mobile number to the +91-XXXXXXXXXX display form.

    Accepted input formats:
        918688977412  →  +91-8688977412
        8688977412    →  +91-8688977412
        Any other     →  returned as-is (safe fallback)
    """
    phone = phone.strip()
    if phone.startswith("91") and len(phone) == 12:
        return f"+91-{phone[2:]}"
    if len(phone) == 10:
        return f"+91-{phone}"
    return phone


def is_valid_vehicle_reg(reg_no: str) -> tuple[bool, str]:
    """
    Validates an Indian vehicle registration number.
    Returns: (is_valid, cleaned_uppercase_reg_number)
    """
    if not reg_no:
        return False, ""
        
    clean_reg = reg_no.upper().replace(" ", "").replace("-", "")
    
    patterns = [
        # 1. Standard, Old, Delhi, EV, Commercial: KA01AB1234, MH011234, DL1T2468, DL3CAF1234
        r"^[A-Z]{2}\d{1,2}[A-Z]{0,3}\d{1,4}$",
        # 2. Bharat Series: 22BH1234AA
        r"^\d{2}BH\d{4}[A-Z]{1,2}$",
        # 3. Diplomatic: 77CD1, 11CC432
        r"^\d{1,3}[A-Z]{2}\d{1,6}$",
        # 4. Military: 25B123456P
        r"^\d{2}[A-Z]\d{1,6}[A-Z]$",
        # 5. Temporary: TS07TR2025123 (Restricted to TR/TC/TMP to prevent false positives)
        r"^[A-Z]{2}\d{1,2}(?:TR|TC|TMP)\d{4,7}$"
    ]
    
    for pattern in patterns:
        if re.match(pattern, clean_reg):
            return True, clean_reg
            
    return False, clean_reg




def normalize_text(text: str) -> str:
    """Normalize user text for robust keyword matching."""
    t = (text or "").lower()
    corrections = {
        "renwal": "renew",
        "renwe": "renew",
        "renw": "renew",
        "estimtae": "estimate",
        "estmate": "estimate",
        "estimat": "estimate",
        "estimte": "estimate",
        "quate": "quote",
        "quoute": "quote",
        "polciy": "policy",
        "premuim": "premium",
        "prmium": "premium",
    }
    for wrong, right in corrections.items():
        t = t.replace(wrong, right)
    return t.strip()


def classify_insurance_intent_request(text: str) -> str | None:
    """
    Return an explicit insurance flow intent from user text, or None.

    Uses broad keyword + semantic pattern matching so natural language
    requests like "i want to renew my insurance" or "can I get a quote"
    are reliably classified as action intents — not knowledge queries.
    """
    t = normalize_text(text)

    # ── RENEWAL action keywords ──────────────────────────────────────────
    # Covers: explicit requests, natural language, typos, mixed phrasing
    renew_kw = [
        # Direct action phrases
        "renew my", "renew my insurance", "renew insurance", "renew my policy",
        "renew policy", "renewal of my", "renewal for my",
        "want to renew", "want to renew my", "i want to renew",
        "i want renew", "i want my renew", "i want renewal",
        "need to renew", "need renewal", "looking to renew",
        "renew now", "renew today", "renewal request", "request renewal",
        "policy renew", "policy renew karna", "policy lena",
        # New policy / purchase
        "new policy for my", "buy insurance for", "purchase policy",
        "buy a policy", "take insurance", "take a policy",
        "get insurance for my", "apply for insurance",
        "i want insurance", "i need insurance for my",
        # Colloquial / short
        "do renewal", "start renewal", "process renewal",
        "book renewal", "schedule renewal", "renewal", "renew"
    ]

    # ── ESTIMATE action keywords ─────────────────────────────────────────
    # Covers: quote, estimate, premium calculation requests
    estimate_kw = [
        # Direct estimate/quote requests
        "get estimate", "get an estimate", "get a estimate",
        "request estimate", "request a quote", "request quote",
        "need estimate", "need a quote", "need quote",
        "want estimate", "want a quote", "want quote",
        "want an estimate", "i want estimate", "i want a quote",
        "send estimate", "give me estimate", "give me a quote",
        "give estimate", "share estimate", "send quote",
        "estimate", "quote",
        # Premium/price calculation (must be part of an action phrase)
        "calculate premium", "calculate premium for my",
        "how much for my car", "how much for my vehicle",
        "how much will it cost for my", "how much does it cost for my",
        "quote for my car", "quote for my vehicle",
        "estimate for my car", "estimate for my vehicle",
        "premium estimate", "insurance estimate for my",
        "insurance quote for my", "premium for my car",
        "premium for my vehicle", "cost of insurance for my",
        "price of insurance for my",
        # Action-oriented short forms
        "get quote", "get a quote", "get me a quote",
        "get me estimate", "get me an estimate",
        "i need an estimate", "i need a estimate",
        "i need quote", "can i get estimate", "can i get a quote",
        "can you give estimate", "can you give me estimate",
        "can you give quote", "can you give me quote",
    ]

    # ── HISTORY keywords ─────────────────────────────────────────────────
    history_kw = [
        "past policy", "previous policy", "old policy", "my history",
        "last premium", "last policy", "my records", "policy history",
        "insurance history", "show my policies", "my past insurance",
        "my previous insurance",
    ]

    # ── ADVISOR keywords ─────────────────────────────────────────────────
    advisor_kw = [
        "talk to", "speak to", "speak with", "talk with",
        "human", "agent", "advisor", "adviser",
        "customer care", "customer support", "support team",
        "contact advisor", "call me", "call back",
        "connect me", "connect to advisor", "real person",
    ]

    if any(k in t for k in renew_kw):
        return "RENEW_INSURANCE"
    if any(k in t for k in estimate_kw):
        return "GET_ESTIMATE"
    if any(k in t for k in history_kw):
        return "INSURANCE_HISTORY"
    if any(k in t for k in advisor_kw):
        return "TALK_TO_ADVISOR"
    return None


def is_insurance_knowledge_query(text: str) -> bool:
    """
    Return True ONLY for purely informational insurance questions.

    CRITICAL: This must return False for ANY action request — the user
    wanting to renew, get an estimate, etc. must NEVER be classified as
    a knowledge query.  classify_insurance_intent_request() is the
    definitive gatekeeper — if it returns an intent, we are NOT in
    knowledge-query territory.

    IMPORTANT: "what is the premium amount", "how is premium calculated",
    "how much does insurance cost in general" etc. are KNOWLEDGE queries —
    the user is asking for information, NOT requesting a quote for their
    specific vehicle.  These must return True so the AI expert answers them
    and the estimate flow is NOT triggered.
    """
    if not text:
        return False

    t = normalize_text(text)

    # ── PRIORITY 1: Pure knowledge question patterns ─────────────────────
    # Check these BEFORE the action-intent gate so that questions like
    # "what is the premium amount and how is it calculated" are never
    # misrouted to the estimate flow.
    #
    # These phrases unambiguously mean the user wants INFORMATION,
    # not to initiate a quote/estimate for their specific vehicle.
    definitive_knowledge_phrases = [
        # Premium / cost information questions
        "what is the premium", "what is premium", "what is the cost",
        "how is premium calculated", "how is the premium calculated",
        "how is premium", "how premium is calculated",
        "how it is calculated", "how is it calculated",
        "what is the premium amount", "premium amount",
        "how much is the premium", "how is insurance premium",
        "how is insurance cost", "how is insurance calculated",
        "how much does insurance cost", "how much is insurance in general",
        "how is the cost calculated", "how do they calculate",
        "what factors affect premium", "what affects premium",
        "what affects insurance", "factors for premium",
        "what determines premium", "what determines the premium",
        # Coverage / policy knowledge
        "what is comprehensive", "what is third party",
        "what is own damage", "what is od", "what is tp",
        "what is saod", "what does saod mean",
        "what does comprehensive cover", "what does third party cover",
        "what is covered", "what is not covered", "what is excluded",
        "difference between comprehensive", "difference between third party",
        "comprehensive vs third party", "third party vs comprehensive",
        # NCB / IDV / add-ons
        "what is ncb", "what is no claim bonus", "how does ncb work",
        "how ncb works", "how much ncb", "what is idv",
        "what is insured declared value", "how is idv calculated",
        "what is zero depreciation", "what is nil depreciation",
        "what is engine protection", "what is roadside assistance",
        "what is return to invoice", "what is pa cover",
        "what is personal accident", "what are add ons", "what are addons",
        # Claim / process knowledge
        "what is claim process", "how to raise a claim",
        "how to file a claim", "claim process", "claim procedure",
        "how does claim work", "how claims work", "cashless claim",
        "what is reimbursement", "claim settlement",
        # Policy / lapse / renewal knowledge (informational)
        "what happens if policy lapses", "what is grace period",
        "what is policy lapse", "what is break in insurance",
        "what is fresh insurance", "what is renewal", "how does renewal work",
        "what is multi year policy", "what is long term policy",
        # General questions with question words
        "explain insurance", "explain premium", "explain coverage",
        "tell me about insurance", "tell me about premium",
        "describe insurance", "how does insurance work",
        "how does motor insurance work", "how does vehicle insurance work",
        "what is motor insurance", "what is vehicle insurance",
        "what is car insurance",
    ]
    if any(phrase in t for phrase in definitive_knowledge_phrases):
        return True

    # ── PRIORITY 2: Flexible pattern matching for questions ────────────────
    # Catches variations like "how the premium amount is calculated"
    import re as _re
    
    # Informational 'how' questions about premium/cost
    if _re.search(r'\bhow\s+.*\b(premium|cost|price|amount|idv|ncb)\b.*\b(calculated|determined|worked|work|decided|comes)\b', t):
        return True
        
    # 'what is' questions about insurance concepts
    if _re.search(r'\bwhat\s+is\s+.*\b(premium|cost|price|coverage|policy|renewal|ncb|idv|claim|addon|comp|third)\b', t):
        return True

    # 'explain' / 'tell me' patterns
    if _re.search(r'\b(explain|tell me|detail|describe|what is|how does)\b.*\b(insurance|premium|renewal|claim|policy)\b', t):
        return True

    # ── PRIORITY 3: Action-intent check is AUTHORITATIVE ─────────────────
    # If the text resolves to a concrete flow action, it is NOT a
    # knowledge query — even if it also contains question words.
    if classify_insurance_intent_request(text) is not None:
        return False

    # ── Hard-block: explicit action verbs that signal "do something" ─────
    # These phrases indicate the user wants an action, not an explanation.
    action_signals = [
        "i want to", "i want", "i need to", "i need", "i would like to",
        "i'd like to", "please renew", "please give", "please send",
        "please provide", "please get", "please calculate",
        "can you renew", "can you give", "can you send",
        "help me renew", "help me get", "help me with renewal",
        "help me with estimate", "start renewal", "begin renewal",
        "do renewal", "do estimate", "initiate renewal",
    ]
    if any(sig in t for sig in action_signals):
        # Only treat as knowledge if it's clearly a "how do I" question
        # not a "I want to" request.
        how_question = any(q in t for q in [
            "how do i", "how can i", "how to", "what is", "what are",
            "explain", "tell me about", "describe"
        ])
        if not how_question:
            # It's an action request — not a knowledge query
            return False

    # ── Informational patterns — genuine knowledge questions ─────────────
    info_phrases = [
        "what is", "what are", "how is", "how are", "why is", "why are",
        "when is", "when are", "where is", "where are", "which is",
        "explain", "describe", "clarify", "tell me about",
        "difference between", "compare", "meaning of", "definition of",
        "process of", "procedure for", "policy details", "premium amount",
        "idv", "ncb", "comprehensive", "third party", "own damage",
        "zero depreciation", "claim process", "claim amount",
        "what does", "how does", "how do", "how is premium calculated",
        "what is covered", "what is not covered",
    ]
    if any(phrase in t for phrase in info_phrases):
        return True

    # ── Longer question-form sentences ───────────────────────────────────
    question_terms = [
        "what", "how", "why", "when", "where", "which",
        "tell me", "explain", "describe", "difference", "compare",
    ]
    if len(t.split()) >= 5 and any(term in t for term in question_terms):
        return True

    return False


# ============================================================
# DATE FORMATTING
# ============================================================

def format_date_only(dt) -> str:
    """
    Convert a date / datetime / string value from the DB into dd-mm-yyyy.
    Returns "N/A" for None or unparseable inputs.
    """
    if not dt:
        return "N/A"

    if isinstance(dt, date):          # covers both date and datetime
        return dt.strftime("%d-%m-%Y")

    s = str(dt)
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, fmt).strftime("%d-%m-%Y")
        except ValueError:
            continue

    return s  # safe fallback – never crash


# ============================================================
# APPOINTMENT DATE HELPERS
# ============================================================

def get_remaining_week_dates() -> list:
    """
    Return the remaining dates in the *current* week starting from the day after
    tomorrow up to and including the coming Sunday.

    Used by insurance, sales, and used-cars flows for appointment scheduling.
    """
    today = datetime.now().date()
    start_day = today + timedelta(days=2)

    days_until_sunday = 6 - start_day.weekday()   # Monday=0 … Sunday=6
    if days_until_sunday < 0:
        days_until_sunday = 0

    end_day = start_day + timedelta(days=days_until_sunday)

    dates = []
    current = start_day
    while current <= end_day:
        dates.append(current)
        current += timedelta(days=1)

    return dates


def get_next_week_dates() -> list:
    """
    Return all seven days of *next* week (Monday → Sunday).

    Used by insurance, sales, and used-cars flows for appointment scheduling.
    """
    today = datetime.now().date()
    days_until_next_monday = 7 - today.weekday()
    next_monday = today + timedelta(days=days_until_next_monday)

    return [next_monday + timedelta(days=i) for i in range(7)]


# ============================================================
# APPOINTMENT TIME VALIDATION
# ============================================================

from datetime import datetime, date, timedelta

BOOKING_CUTOFF_HOUR = 18  # 6 PM — no same-day bookings after this hour


def get_smart_default_date() -> tuple[date, bool]:
    """
    Returns the smart default booking date based on current time.

    Rule:
      - Before 6 PM  → today is bookable → return (today, False)
      - At/After 6 PM → today is blocked  → return (tomorrow, True)

    Returns:
        (default_date, was_redirected_to_tomorrow)
        was_redirected_to_tomorrow is True when we auto-advanced past today.

    Used by all flows when customer selects "Today" after cutoff — instead of
    rejecting and re-prompting, we silently advance to tomorrow and inform them.
    """
    now = datetime.now()
    today = now.date()
    if now.hour >= BOOKING_CUTOFF_HOUR:
        return today + timedelta(days=1), True
    return today, False


def is_valid_appointment_slot(appointment_date: date, appointment_time_str: str = None) -> tuple[bool, str]:
    """
    Validate whether an appointment date+time is bookable.

    Rules:
      - If current time >= 6 PM, today is blocked entirely.
      - If current time < 6 PM, today is allowed only if the chosen time
        is at least 1 hour from now.
      - Past dates are always blocked.

    Args:
        appointment_date: The date the customer wants to book.
        appointment_time_str: Optional time string like "10:30 AM" or "14:00".

    Returns:
        (True, "") if valid.
        (False, reason_message) if invalid.
    """
    now = datetime.now()
    today = now.date()

    # ── Block past dates ────────────────────────────────────────
    if appointment_date < today:
        return False, "⚠️ That date has already passed. Please choose a future date."

    # ── Same-day logic ──────────────────────────────────────────
    if appointment_date == today:
        if now.hour >= BOOKING_CUTOFF_HOUR:
            return False, (
                f"⚠️ Same-day bookings are not accepted after 6:00 PM.\n"
                f"Please choose a date from tomorrow onwards. 📅"
            )

        # If a specific time was also provided, check it's not too soon
        if appointment_time_str:
            parsed_time = _parse_time(appointment_time_str)
            if parsed_time:
                appointment_dt = datetime.combine(today, parsed_time)
                if appointment_dt <= now + timedelta(hours=1):
                    return False, (
                        f"⚠️ Please book at least 1 hour in advance.\n"
                        f"The earliest available slot today is "
                        f"{(now + timedelta(hours=1)).strftime('%I:%M %p')}. ⏰"
                    )

    return True, ""


def _parse_time(time_str: str):
    """
    Parse a time string into a datetime.time object.
    Supports formats: '10:30 AM', '2:00 PM', '14:00', '9am', etc.
    Returns None if unparseable.
    """
    time_str = time_str.strip()
    for fmt in ("%I:%M %p", "%I:%M%p", "%H:%M", "%I %p", "%I%p"):
        try:
            return datetime.strptime(time_str.upper(), fmt.upper()).time()
        except ValueError:
            continue
    return None


def get_available_booking_dates() -> list:
    """
    Return dates available for booking based on current time.
    
    - Before 6 PM  → today + remaining week + next week
    - After 6 PM   → starts from TOMORROW (today excluded)
    """
    now = datetime.now()
    today = now.date()

    if now.hour >= BOOKING_CUTOFF_HOUR:
        # Push start to tomorrow
        start_day = today + timedelta(days=1)
    else:
        start_day = today

    # Build remaining current week from start_day
    days_until_sunday = 6 - start_day.weekday()
    end_of_week = start_day + timedelta(days=max(days_until_sunday, 0))

    dates = []
    current = start_day
    while current <= end_of_week:
        dates.append(current)
        current += timedelta(days=1)

    return dates


# ============================================================
# AI QUERY GATE  —  is_genuine_query()
# ============================================================
# This is the single source of truth for ALL flows.
#
# PURPOSE:
#   Determine whether a user's free-text input is a genuine
#   question/query that should be answered by the AI, OR just
#   a flow input (reg number, name, date, address, etc.) that
#   the flow itself should handle with a re-prompt.
#
# RULE:
#   AI responds ONLY when the user is genuinely asking a question.
#   For everything else (form inputs, accidental text, short
#   words that look like menu selections) the flow re-prompts.
#
# STATES WHERE AI IS NEVER CALLED:
#   - Any state that expects a structured input:
#       vehicle reg number, name, address, date, time slot,
#       phone number, car brand/model/year, city, loan amount.
#   These states should handle bad input with a polite re-prompt,
#   NOT by routing to the AI.
# ============================================================

# States in each flow that expect raw user text input (NOT questions).
# AI should NEVER be triggered in these states regardless of what the user types.
_STRUCTURED_INPUT_STATES = {
    # Insurance — vehicle lookup and estimate
    "INSURANCE_LOOKUP",             # expects vehicle reg number
    # NOTE: INSURANCE_ESTIMATE_NAME and STATE_4_NAME are NOT listed here.
    # They use _handle_mid_flow_knowledge_query() to intercept knowledge questions
    # BEFORE form validation, then re-prompt the form field after answering.
    # Listing them here would prevent knowledge queries from reaching the AI.
    "INSURANCE_ESTIMATE_LINK_SENT", # link sent, waiting for upload or buttons
    # NOTE: STATE_4_ADDRESS is NOT listed here — the interceptor handles it too.
    # NOTE: STATE_4_RENEW_TYPE, STATE_4_MODE, STATE_4_DATE, STATE_4_LATER_WEEK,
    # STATE_4_NEXT_WEEK, STATE_4_SLOT, STATE_4_DONE are intentionally NOT listed here.
    # Those states have their own inline keyword resolvers that run first.
    # When the resolver can't match the input (e.g. a genuine question),
    # the flow calls _route_via_ai() which needs is_genuine_query() to return True.
    "STATE_5_ADVISOR",              # advisor handoff
    "INSURANCE_AGENT_CONFIRMATION", # human agent confirmation
    "INSURANCE_VEHICLE_FOUND",      # after lookup, list/menu state

    # Sales — car selection and customer collection
    "SALES_COLLECT_NAME",           # expects customer name
    "SALES_COLLECT_PHONE",          # expects phone number
    "SALES_COLLECT_ADDRESS",        # expects address (home visit)
    "SALES_AGENT_CONFIRMATION",     # human agent confirmation

    # Refinancing — customer collection and loan details
    "REFINANCING_ASK_NAME",         # expects name
    "REFINANCING_ASK_PHONE",        # expects phone
    "REFINANCING_ASK_CITY",         # expects city
    "REFINANCING_ASK_BRAND_OTHER",  # expects brand name
    "REFINANCING_ASK_MODEL_OTHER",  # expects model name
    "REFINANCING_ASK_MODEL",        # expects model name
    "REFINANCING_ASK_YEAR",         # expects year
    "REFINANCING_ASK_HAS_LOAN",    # loan status selection
    "REFINANCING_ASK_REMAINING_AMT",# remaining loan amount
    "REFINANCING_ASK_LOAN_NEEDED", # required loan amount
    "REFINANCING_ASK_CONTACT_TIME", # preferred contact time
    "REFINANCING_AGENT_CONFIRMATION", # human agent confirmation

    # Insurance: name/age collection states (prevent AI interference)
    "STATE_4_WAITING_NAME",
    "STATE_4_WAITING_AGE",
    "STATE_5_WAITING_NAME",
    "STATE_5_WAITING_AGE",

    # Used Cars: name/data collection
    "USED_VALUATION_COLLECT_NAME",
    "USED_VALUATION_COLLECT_PHONE",
    "USED_VALUATION_COLLECT_LOCATION",
    "USED_BOOK_COLLECT_NAME",
    "USED_BOOK_COLLECT_LOCATION",
    "USED_BOOK_COLLECT_LICENSE",
    "USED_CALLBACK_COLLECT_NAME",
    "USED_CALLBACK_COLLECT_PHONE",
    "USED_CALLBACK_COLLECT_NEED",
    "EXCH_COLLECT_NAME",
    "EXCH_COLLECT_CITY",
    "EXCH_FINANCE_CALLBACK",
    "EXCH_TD_ADDRESS",
    "EXCH_BRAND",
    "EXCH_BRAND_ENTER",
    "EXCH_MODEL",
    "EXCH_MODEL_ENTER",
    "EXCH_YEAR",
    "EXCH_FUEL",
    "EXCH_TRANS",
    "EXCH_KM",
    "EXCH_OWNERS",
    "EXCH_CONDITION",
    "EXCH_INSURANCE",
    "EXCH_DOCS",
    "EXCH_TYPE",
    "EXCH_BUDGET",
    "EXCH_NEW_BRAND",
    "EXCH_NEW_BRAND_ENTER",
    "EXCH_NEW_MODEL",
    "EXCH_NEW_MODEL_ENTER",
    "EXCH_NEW_FUEL",
    "EXCH_NEW_TRANS",

    # Service: name/address collection (prevent AI interference)
    "waiting_full_name",
    "waiting_phone_number",
    "waiting_pickup_address",
    "waiting_drop_address_input",
    "waiting_special_instructions",
    "waiting_city_input",
    "waiting_vehicle_model_input",
    "waiting_odo_reading_input",
    "SERVICE_COLLECT_NAME",
    "SERVICE_COLLECT_PHONE",
    "SERVICE_COLLECT_ADDRESS",
    "SERVICE_LOOKUP",               # service: expects vehicle reg number
    "SERVICE_SELECT_SERVICE_TYPE",  # service type selection
    "SERVICE_AGENT_CONFIRMATION",   # human agent confirmation
}

# States that match input-style flows by prefix.
_STRUCTURED_INPUT_STATE_PREFIXES = {
    # NOTE: Flow-specific prefixes like 'SERVICE_', 'USED_', 'SALES_', 'REFINANCING_' 
    # are INTENTIONALLY REMOVED from here to allow is_genuine_query()
    # to check the actual text for questions mid-flow.
}

# Question/query indicator words and patterns.
_QUESTION_WORDS = {
    "what", "which", "who", "when", "where", "why", "how",
    "is", "are", "was", "were", "will", "would", "can", "could",
    "do", "does", "did", "should", "has", "have", "had",
    "tell me", "explain", "describe", "clarify", "difference",
    "compare", "versus", "vs", "meaning", "definition",
    "help", "assist", "support", "information", "info",
    "know", "understand", "find out", "find", "show me",
    "calculate", "estimate", "quote", "cost", "price", "rate",
    "available", "offer", "provide", "include", "cover",
    "benefit", "feature", "advantage", "work", "happen",
    "process", "procedure", "step", "guide", "recommend",
    "issue", "problem", "fault", "noise", "leak", "light", "warning",
    "vibration", "smell", "smoke", "repair", "fix", "check", "service",
    "appointment", "booking", "advisor", "agent", "human", "person",
}

# Minimum word count for a message to be considered a query.
_MIN_QUERY_WORDS = 2


def is_genuine_query(text: str, state: str = "") -> bool:
    """
    Returns True ONLY if the user's text is a genuine question or query
    that should be answered by the AI assistant.

    Returns False for:
      - Vehicle registration numbers (e.g. KA01AB1234)
      - Short inputs (1–2 words) that look like form inputs
      - Pure numbers or alphanumeric codes
      - States that always expect structured form inputs
      - Greetings that should restart the flow, not trigger AI

    Args:
        text  : The raw user message text.
        state : The current flow state (used to block AI in form states).

    Returns:
        bool — True = let AI respond, False = flow handles it.
    """
    if not text:
        return False

    t = text.strip()
    t_lower = t.lower()
    words = t_lower.split()
    word_count = len(words)

    # ── 1. Block AI entirely in structured-input states ─────────────────
    if state in _STRUCTURED_INPUT_STATES or any(str(state).startswith(prefix) for prefix in _STRUCTURED_INPUT_STATE_PREFIXES):
        print(f"[query_gate] BLOCK — structured input state: {state}")
        return False

    # ── 1b. Explicit Intent Check ───────────────────────────────────────
    # If the text matches a known insurance intent (Renew, Estimate, etc.),
    # allow it through so the AI router can execute the flow switch.
    if classify_insurance_intent_request(text):
        print(f"[query_gate] ALLOW — explicit insurance intent: '{t}'")
        return True

    # ── 2. Vehicle registration number pattern ───────────────────────────
    #    Format: 2 letters + 2 digits + optional 2 letters + 4 digits
    #    e.g. KA01AB1234, KL21W2285, MH12DE1433
    if re.match(r'^[A-Za-z]{2}\d{2}[A-Za-z]{0,3}\d{4}$', t.replace(' ', '')):
        print(f"[query_gate] BLOCK — looks like vehicle reg: '{t}'")
        return False

    # ── 3. Pure number or very short code ───────────────────────────────
    if re.match(r'^\d+$', t):
        print(f"[query_gate] BLOCK — pure number: '{t}'")
        return False

    # ── 4. Single word that's just an alphanumeric code ─────────────────
    if word_count == 1 and re.match(r'^[A-Za-z0-9_]{1,20}$', t):
        # Single short words could be menu IDs, codes, names.
        # Exception: if it's a known question word, let it through.
        if t_lower not in _QUESTION_WORDS:
            print(f"[query_gate] BLOCK — single non-question word: '{t}'")
            return False

    # ── 5. Too short to be a real question (1–2 words, no question mark) ─
    if word_count < _MIN_QUERY_WORDS and '?' not in t:
        # Allow known question words even if short (e.g. "how?", "why?")
        if not any(w in _QUESTION_WORDS for w in words):
            print(f"[query_gate] BLOCK — too short, no question mark: '{t}'")
            return False

    # ── 6. Explicit question mark → definitely a query ──────────────────
    if '?' in t:
        print(f"[query_gate] ALLOW — has question mark: '{t}'")
        return True

    # ── 7. Starts with or contains a question word ───────────────────────
    if words and words[0] in _QUESTION_WORDS:
        print(f"[query_gate] ALLOW — starts with question word: '{t}'")
        return True

    if any(qw in t_lower for qw in ["tell me", "explain", "describe", "clarify",
                                      "show me", "find out", "help me", "i want to know",
                                      "what is", "what are", "how much", "how many",
                                      "how does", "how do", "can you", "could you",
                                      "i need help", "please explain", "please tell",
                                      "documents", "what docs", "renewal", "requirements",
                                      "how to renew", "procedure", "process"]):
        print(f"[query_gate] ALLOW — contains query phrase: '{t}'")
        return True

    # ── 8. Longer sentences that look like natural language queries ───────
    #    If 5+ words and NOT just a list of proper nouns or numbers,
    #    it's probably a question even without a question word.
    if word_count >= 5:
        # Check if it contains answer-like or conversational confirmation phrases
        answer_phrases = [
            "is fine", "is okay", "is ok", "is good", "works for me", "fine for me",
            "doesn't matter", "anytime", "any time", "i prefer", "make it",
            "schedule it", "book for", "perfect", "i am free", "i'm free",
            "will be free", "let's do", "i will come"
        ]
        if any(ans in t_lower for ans in answer_phrases):
            # If the user is just answering the prompt conversationally, it's not a query
            # (e.g. "12pm is fine for me", "tomorrow works for me")
            print(f"[query_gate] BLOCK — contains answer phrase: '{t}'")
            return False

        # Check it's not just a sequence of names/codes
        non_alpha = sum(1 for w in words if not re.match(r'^[A-Za-z]+$', w))
        if non_alpha <= 1:  # mostly letters = natural language
            print(f"[query_gate] ALLOW — long natural language sentence: '{t}'")
            return True

    print(f"[query_gate] BLOCK — not identified as a genuine query: '{t}'")
    return False


# ============================================================
# SMART DATE RESOLVER
# Maps natural language dates to IDs (e.g. '24th' -> 'DATE_20240424')
# ============================================================

def resolve_date_from_text(text: str, available_dates: list, prefix: str) -> str | None:
    """
    Intelligently match user's free-text date input to one of the available_dates.
    Uses multiple strategies: ordinal matching, month matching, weekday matching, and AI fallback.
    Handles dates like "4th may", "5 may", "may 5", "24", "Monday", "tomorrow", etc.
    """
    if not text or not available_dates:
        return None
    
    t = text.lower().strip()
    print(f"📅 [utils] resolve_date_from_text: '{text}' (normalized: '{t}')")
    
    # ── Remove ordinal suffixes (st, nd, rd, th) ──────────────────────────
    t_clean = re.sub(r'(st|nd|rd|th)\b', '', t)
    print(f"   Cleaned ordinals: '{t_clean}'")
    
    # Extract all numbers and find the first valid day number
    nums = re.findall(r'\d+', t_clean)
    day_num = None
    if nums:
        day_num = int(nums[0])
        if 1 <= day_num <= 31:
            print(f"   Extracted day number: {day_num}")
        else:
            day_num = None
    
    # ── Month name mapping (full and abbreviated) ─────────────────────────
    month_map = {
        # Full month names
        "january": 1, "february": 2, "march": 3, "april": 4, "may": 5, "june": 6,
        "july": 7, "august": 8, "september": 9, "october": 10, "november": 11, "december": 12,
        # Abbreviated month names
        "jan": 1, "feb": 2, "mar": 3, "apr": 4, "jun": 6,
        "jul": 7, "aug": 8, "sep": 9, "sept": 9, "oct": 10, "nov": 11, "dec": 12,
        # Hindi months
        "january": 1, "phbruary": 2, "march": 3, "april": 4, "may": 5,
    }
    
    month_num = None
    for mname, mnum in month_map.items():
        if mname in t_clean:
            month_num = mnum
            print(f"   Extracted month: {mname} → {mnum}")
            break
    
    # ── Strategy 1: Day + Month (e.g. "4th may", "5 april") ──────────────
    if day_num and month_num:
        print(f"   Trying day+month match: day={day_num}, month={month_num}")
        for d in available_dates:
            if d.day == day_num and d.month == month_num:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ Day+month match found: {d.strftime('%Y-%m-%d')} → {result}")
                return result
        print(f"   ❌ No date found for {day_num}/{month_num}")
    
    # ── Strategy 2: Day only (e.g. "24", "5") - if text is very short ───
    if day_num and len(t) <= 5:
        print(f"   Trying day-only match: day={day_num}")
        for d in available_dates:
            if d.day == day_num:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ Day-only match found: {d.strftime('%Y-%m-%d')} → {result}")
                return result
    
    # ── Strategy 3: Weekday name (e.g. "Monday", "Wed", "Friday") ────────
    weekday_map = {
        "monday": 0, "mon": 0, "tuesday": 1, "tue": 1, "wednesday": 2, "wed": 2,
        "thursday": 3, "thu": 3, "friday": 4, "fri": 4, "saturday": 5, "sat": 5,
        "sunday": 6, "sun": 6
    }
    for wday_name, wday_idx in weekday_map.items():
        if wday_name in t_clean:
            print(f"   Trying weekday match: {wday_name} (index={wday_idx})")
            for d in available_dates:
                if d.weekday() == wday_idx:
                    result = f"{prefix}{d.strftime('%Y%m%d')}"
                    print(f"   ✅ Weekday match found: {d.strftime('%Y-%m-%d')} → {result}")
                    return result
            break
    
    # ── Strategy 4: Relative dates ──────────────────────────────────────
    today = date.today()
    if "today" in t_clean or "this day" in t_clean:
        for d in available_dates:
            if d == today:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ 'Today' match: {d.strftime('%Y-%m-%d')} → {result}")
                return result
    
    if "tomorrow" in t_clean or "next day" in t_clean:
        tomorrow = today + timedelta(days=1)
        for d in available_dates:
            if d == tomorrow:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ 'Tomorrow' match: {d.strftime('%Y-%m-%d')} → {result}")
                return result
    
    # ── Strategy 5: Groq AI fallback for complex/multilingual inputs ─────
    if len(available_dates) > 0:
        try:
            dates_list = "\n".join(
                [f"- {d.strftime('%A')}, {d.strftime('%d %B %Y')} (ID: {prefix}{d.strftime('%Y%m%d')})"
                 for d in sorted(available_dates)]
            )
            
            prompt = f"""Match the user's date input to ONE exact date from the list below.
The date might be in English, Hindi, Tamil, Telugu, or any language.
Extract the specific date they mentioned and find the closest match.

AVAILABLE DATES:
{dates_list}

USER MESSAGE: "{text}"

RULES:
1. If they mention a specific day/month/date, find EXACTLY that date
2. If ambiguous (e.g., "24"), choose the next occurrence of day 24
3. If they say "today", "tomorrow", "Monday", match to that day
4. Return ONLY valid JSON: {{"matched_id": "<full ID from list>", "reason": "<short reason>"}}
5. If NO match possible, return {{"matched_id": "NONE", "reason": "no match found"}}"""

            response = _client.chat.completions.create(
                model=_MODEL_NAME,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=100,
                response_format={"type": "json_object"}
            )
            
            result = json.loads(response.choices[0].message.content.strip())
            matched_id = result.get("matched_id", "NONE")
            reason = result.get("reason", "")
            
            print(f"🤖 [utils] AI fallback: '{text}' → '{matched_id}' (reason: {reason})")
            
            if matched_id and matched_id != "NONE" and matched_id.startswith(prefix):
                return matched_id
            
        except Exception as e:
            print(f"❌ [utils] AI fallback error: {e}")
    
    print(f"   ❌ No match found for: '{text}'")
    return None


# ============================================================
# INTELLIGENT FLOW-AWARE QUERY COMPREHENSION
# Understands customer queries BEFORE rigidly following flow
# ============================================================
def understand_customer_in_flow_context(phone: str, user_text: str, current_state: str, 
                                        flow_context: dict = None) -> dict:
    """
    Use LLM to intelligently understand what customer is really asking/doing,
    even within a predefined flow state.
    
    This MUST be called FIRST in flow handlers to determine if:
    1. Customer is answering the flow question normally → return action="CONTINUE_FLOW"
    2. Customer is asking a question → return action="ANSWER_QUERY" + answer
    3. Customer wants to switch flows/go back → return action="SWITCH_CONTEXT" + action
    4. Customer needs clarification → return action="CLARIFY"
    5. Customer input is ambiguous → return action="AMBIGUOUS"
    
    Returns dict with keys:
    - action: one of ["CONTINUE_FLOW", "ANSWER_QUERY", "SWITCH_CONTEXT", "CLARIFY", "AMBIGUOUS"]
    - should_proceed_with_flow: bool (True if flow should continue normally)
    - response: str (AI's response if action is not CONTINUE_FLOW)
    - extracted_data: dict (normalized/extracted data if extractable)
    - flow_action: str (specific action like "BACK", "MAIN_MENU", "CHANGE_CRITERIA", etc.)
    """
    try:
        if not user_text or not user_text.strip():
            return {
                "action": "AMBIGUOUS",
                "should_proceed_with_flow": False,
                "response": "I didn't catch that. Could you please say that again?",
                "extracted_data": {},
                "flow_action": None
            }
        
        flow_context = flow_context or {}
        
        system_prompt = f"""You are an intelligent flow assistant for an automotive chatbot.
Your job is to understand what the customer REALLY wants, even when they're in the middle of a form/flow.

CURRENT FLOW STATE: {current_state}
FLOW CONTEXT: {json.dumps(flow_context, indent=2)}

Analyze the customer's message and determine:
1. Are they answering the current question normally? (e.g., flow expects "Brand" and they say "Hyundai")
2. Are they asking a question about the product/service?
3. Do they want to go back/switch flows/cancel?
4. Are they expressing concerns or needs that aren't aligned with the current step?
5. Is it ambiguous what they want?

Return ONLY valid JSON with this structure:
{{
    "action": "<CONTINUE_FLOW|ANSWER_QUERY|SWITCH_CONTEXT|CLARIFY|AMBIGUOUS>",
    "confidence": <0.0-1.0>,
    "should_proceed_with_flow": <true|false>,
    "response": "<Your intelligent response to customer>",
    "extracted_data": {{"key": "value"}},
    "flow_action": "<specific action like BACK, MAIN_MENU, CHANGE_CRITERIA, TALK_TO_ADVISOR, or null>"
}}

Guidelines:
- If they clearly answer the question, use CONTINUE_FLOW
- If they ask "what is...", "how does...", "tell me about...", use ANSWER_QUERY
- If they say "go back", "main menu", "talk to someone", use SWITCH_CONTEXT with flow_action
- If they express doubt/concern, use CLARIFY or ANSWER_QUERY
- If unclear, use AMBIGUOUS
- Always be helpful and conversational
- Acknowledge their concern before continuing the flow
"""

        user_prompt = f'Customer message: "{user_text}"'

        response = _client.chat.completions.create(
            model=_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3,
            max_tokens=500,
            response_format={"type": "json_object"}
        )
        
        result = json.loads(response.choices[0].message.content.strip())
        
        print(f"🧠 [Flow Context Understanding] State={current_state}")
        print(f"   Action: {result.get('action')}")
        print(f"   Confidence: {result.get('confidence')}")
        print(f"   Flow Action: {result.get('flow_action')}")
        
        return result
        
    except Exception as e:
        print(f"❌ Flow context understanding error: {e}")
        # Fallback: assume they're trying to continue the flow
        return {
            "action": "CONTINUE_FLOW",
            "should_proceed_with_flow": True,
            "response": None,
            "extracted_data": {},
            "flow_action": None,
            "confidence": 0.5
        }


# ============================================================
# CUSTOMER NAME VALIDATOR & CLEANER
# ============================================================

def validate_and_clean_name(text: str) -> tuple[bool, str, str]:
    """
    Validates if the user input represents a valid/meaningful customer name.
    Returns: (is_valid, clean_name, fallback_message)
    """
    t = text.strip()
    if not t:
        return False, "", "I'm sorry, I didn't receive a name. Could you please provide your name? 👤"
    
    t_lower = t.lower()
    
    # 1. Repeating characters check (e.g., "sss", "ccc", "aaaa")
    if len(t) > 1 and len(set(t_lower)) == 1:
        return False, "", "I'm sorry, that doesn't seem to be a valid name. Could you please share your correct name? 👤"
        
    # 2. Too short or pure digits
    if len(t) < 2 or t.isdigit():
        return False, "", "I'm sorry, that doesn't seem to be a valid name. Could you please share your correct name? 👤"
        
    # 3. Known common greeting/cancellation/refusal words that shouldn't be names
    refusal_words = {"no", "yes", "stop", "cancel", "bye", "hi", "hello", "hey", "test", "none", "na", "n/a", "ok", "okay"}
    if t_lower in refusal_words:
        return False, "", "I'm sorry, that doesn't seem to be a valid name. Could you please share your correct name? 👤"
        
    # Call LLM for expert validation
    messages = [
        {
            "role": "system",
            "content": "You are a professional name validator for an automotive customer support chatbot. Respond ONLY with a valid JSON object."
        },
        {
            "role": "user",
            "content": f"""Analyze the user input to determine if it represents a valid customer name.
User Input: "{t}"

Rules:
1. is_valid (boolean): True if it is a realistic first name, last name, or full name, or if a realistic name can be extracted. False if it is gibberish/random letters (e.g., sss, cc, xyz, abc, qwe, asdf), placeholder name (e.g., test, dummy, user), digit strings, or conversational filler with no name.
2. clean_name (string or null): Properly capitalized extracted name (e.g., "Amit Sharma" or "Rahul"). Null if invalid.
3. fallback_message (string or null): A polite, professional fallback message asking for their correct name to update their details if invalid. Null if valid.

Return JSON format:
{{"is_valid": true/false, "clean_name": "extracted_name" or null, "fallback_message": "message" or null}}"""
        }
    ]
    
    try:
        result = smart_llm_call(
            messages=messages,
            temperature=0.1,
            max_tokens=150,
            response_format={"type": "json_object"},
            as_json=True
        )
        is_valid = result.get("is_valid", False)
        clean_name = result.get("clean_name")
        fallback = result.get("fallback_message")
        
        if is_valid and clean_name:
            return True, clean_name, ""
        else:
            if not fallback:
                fallback = "I'm sorry, that doesn't seem to be a valid name. Could you please share your correct name? 👤"
            return False, "", fallback
    except Exception as e:
        print(f"[name_validator] LLM validation error: {e}")
        # Fallback to basic regex if LLM fails
        if re.match(r'^[A-Za-z\s\.\-\']{2,40}$', t) and not any(w in refusal_words for w in t_lower.split()):
            if len(set(t_lower.replace(" ", ""))) > 1:
                return True, t.title(), ""
        return False, "", "I'm sorry, that doesn't seem to be a valid name. Could you please share your correct name? 👤"

# ============================================================
# CUSTOMER LOCATION VALIDATOR & CLEANER
# ============================================================

def validate_and_clean_location(text: str) -> tuple[bool, str, str]:
    """
    Validates if the user input represents a valid/meaningful location, address, or city.
    Returns: (is_valid, clean_location, fallback_message)
    """
    t = text.strip()
    if not t:
        return False, "", "I'm sorry, I didn't receive a location. Could you please provide your valid location or address? 📍"
    
    t_lower = t.lower()
    
    # 1. Repeating characters check (e.g., "sss", "ccc", "aaaa")
    if len(t) > 1 and len(set(t_lower)) == 1:
        return False, "", "I'm sorry, that doesn't seem to be a valid location. Could you please provide a real address or neighborhood? 📍"
        
    # 2. Too short (unless it's a known short abbreviation like "mg") or pure digits without text
    if t.isdigit():
        return False, "", "I'm sorry, please provide a street name, neighborhood, or city instead of just numbers. 📍"
        
    # 3. Known common greeting/cancellation/refusal words that shouldn't be locations
    refusal_words = {"no", "yes", "stop", "cancel", "bye", "hi", "hello", "hey", "test", "dummy", "none", "na", "n/a", "ok", "okay", "i don't know", "skip"}
    if t_lower in refusal_words:
        return False, "", "I'm sorry, that doesn't seem to be a valid location. Could you please provide your valid address or neighborhood? 📍"
        
    # Call LLM for expert validation
    messages = [
        {
            "role": "system",
            "content": "You are a professional location and address validator for an automotive customer support chatbot in India. Respond ONLY with a valid JSON object."
        },
        {
            "role": "user",
            "content": f"""Analyze the user input to determine if it represents a valid location, city, neighborhood, or full address.
User Input: "{t}"

Rules:
1. is_valid (boolean): True if it is a realistic location, neighborhood, city, landmark, or full address. Valid examples include common short abbreviations (e.g., "HSR", "BTM", "ECity", "RR Nagar", "JP Nagar"), street names ("MG Road"), single words ("Whitefield", "Marathahalli", "Bangalore"), and structured addresses. False if it is gibberish/random letters (e.g., "lls", "abc", "rrd", "xyz", "qwerty"), conversational filler (e.g., "ok", "yes", "dummy"), or pure numbers without context (e.g., "12345").
2. clean_location (string or null): Properly capitalized extracted location (e.g., "HSR Layout", "BTM", "MG Road"). Null if invalid.
3. fallback_message (string or null): A polite, professional fallback message asking for their correct location/address if invalid. Null if valid.

Return JSON format:
{{"is_valid": true/false, "clean_location": "extracted_location" or null, "fallback_message": "message" or null}}"""
        }
    ]
    
    try:
        from llm_config import smart_llm_call
        result = smart_llm_call(
            messages=messages,
            temperature=0.1,
            max_tokens=150,
            response_format={"type": "json_object"},
            as_json=True
        )
        is_valid = result.get("is_valid", False)
        clean_loc = result.get("clean_location")
        fallback = result.get("fallback_message")
        
        if is_valid and clean_loc:
            return True, clean_loc, ""
        else:
            if not fallback:
                fallback = "I'm sorry, that doesn't seem to be a valid location. Could you please provide a real address or neighborhood? 📍"
            return False, "", fallback
    except Exception as e:
        print(f"[location_validator] LLM validation error: {e}")
        # Fallback to basic regex if LLM fails: letters/numbers/spaces/commas longer than 2 chars
        if re.match(r'^[A-Za-z0-9\s\,\.\-\#\/]{2,100}$', t) and not any(w in refusal_words for w in t_lower.split()):
            if len(set(t_lower.replace(" ", ""))) > 1:
                return True, t.title(), ""
        return False, "", "I'm sorry, that doesn't seem to be a valid location. Could you please provide a real address or neighborhood? 📍"


# ============================================================
# TIME SLOT & DATE CUTOFF DYNAMIC FILTERING
# ============================================================

def get_slot_start_hour(slot_id: str, slot_title: str = "") -> float:
    """
    Map a slot ID or title to its start hour.
    """
    slot_id_lower = str(slot_id).lower()
    slot_title_lower = str(slot_title).lower() if slot_title else ""
    
    # 1. Morning slots
    if "morning" in slot_id_lower or "morning" in slot_title_lower:
        if "9am" in slot_title_lower or "9-12" in slot_title_lower:
            return 9.0   # 9:00 AM
        return 10.0      # Default 10:00 AM
        
    # 2. Evening slots
    if "evening" in slot_id_lower or "evening" in slot_title_lower:
        if "3-6" in slot_title_lower or "3 - 6" in slot_title_lower:
            return 15.0  # 3:00 PM
        return 16.0      # Default fallback 4:00 PM (starts at 4 PM)
        
    # 3. Afternoon slots
    if "afternoon" in slot_id_lower or "afternoon" in slot_title_lower:
        if "1pm-3pm" in slot_title_lower or "1 pm - 3 pm" in slot_title_lower or "1-3" in slot_title_lower:
            return 13.0  # 1:00 PM
        return 12.0      # Default fallback 12:00 PM
        
    # 4. Anytime slot (starts at latest slot cutoff start: 4:00 PM)
    if "anytime" in slot_id_lower or "anytime" in slot_title_lower:
        return 16.0
        
    return 16.0  # Default fallback

def is_slot_available_today(slot_id: str, slot_title: str = "") -> bool:
    """
    Returns True if the slot has not started yet today (current time < start hour).
    """
    now = datetime.now()
    current_time_float = now.hour + now.minute / 60.0
    start_hour = get_slot_start_hour(slot_id, slot_title)
    return current_time_float < start_hour

def is_booking_date_today(phone: str) -> bool:
    """
    Determines if the customer's currently selected booking date is today.
    """
    from config import USER_STATE
    today_str1 = datetime.now().strftime("%d-%m-%Y")  # e.g., "05-06-2026"
    today_str2 = datetime.now().strftime("%Y-%m-%d")  # e.g., "2026-06-05"
    
    def match_today(val):
        if not val:
            return False
        if isinstance(val, date):
            return val == datetime.now().date()
        val_str = str(val).strip().lower()
        if "today" in val_str:
            return True
        if today_str1 in val_str or today_str2 in val_str:
            return True
        
        # Try extracting 8 digit date (e.g. YYYYMMDD)
        import re
        m = re.search(r'\d{8}', val_str)
        if m:
            if m.group(0) == datetime.now().strftime("%Y%m%d"):
                return True
        return False

    # Check USER_STATE (Insurance, Sales, Used Cars)
    if phone in USER_STATE:
        state_data = USER_STATE[phone]
        if match_today(state_data.get("renew", {}).get("date")):
            return True
        if match_today(state_data.get("preferred_when")) or match_today(state_data.get("preferred_when_raw")):
            return True
        if match_today(state_data.get("test_drive_date")) or match_today(state_data.get("exch_td_date")) or match_today(state_data.get("callback_date")):
            return True

    # Check Service Bot Sessions
    try:
        from flows.service import bot as service_bot
        if phone in service_bot.user_sessions:
            sess = service_bot.user_sessions[phone]
            booking_data = sess.get('booking_data', {})
            if match_today(booking_data.get('date')) or match_today(booking_data.get('selected_date')) or match_today(booking_data.get('appointment_date')):
                return True
            contact_data = sess.get('contact_data', {})
            if match_today(contact_data.get('callback_date')) or match_today(contact_data.get('video_date')):
                return True
    except Exception:
        pass

    return False

def get_latest_possible_slot_start_hour(phone: str) -> float:
    """
    Returns the latest starting slot hour for the user's active flow today.
    """
    # All evening slots across all modules start at 4 PM (16.0).
    return 16.0

def is_today_bookable(phone: str) -> bool:
    """
    Returns True if same-day bookings are still open.
    """
    now = datetime.now()
    current_time_float = now.hour + now.minute / 60.0
    latest_start_hour = get_latest_possible_slot_start_hour(phone)
    return current_time_float < latest_start_hour

def filter_date_options(phone: str, rows_or_buttons: list) -> list:
    """
    Hides the "Today" option if same-day bookings are closed.
    """
    if is_today_bookable(phone):
        return rows_or_buttons
        
    filtered = []
    for item in rows_or_buttons:
        item_id = ""
        item_title = ""
        
        if isinstance(item, dict):
            if item.get("type") == "reply" and "reply" in item:
                item_id = item["reply"].get("id", "")
                item_title = item["reply"].get("title", "")
            else:
                item_id = item.get("id", "")
                item_title = item.get("title", "")
                
        item_id_upper = str(item_id).upper()
        item_title_lower = str(item_title).lower()
        
        is_today_option = (
            "TODAY" in item_id_upper or 
            item_title_lower == "today" or
            "30MIN" in item_id_upper or
            "30 mins" in item_title_lower
        )
        
        if is_today_option:
            print(f"⌛ Hiding Today option for {phone} because same-day booking window has closed.")
            continue
            
        filtered.append(item)
    return filtered

def filter_lapsed_time_slots(phone: str, rows_or_buttons: list) -> list:
    """
    Hides lapsed slots if the selected booking date is Today.
    """
    if not is_booking_date_today(phone):
        return rows_or_buttons
        
    filtered = []
    for item in rows_or_buttons:
        item_id = ""
        item_title = ""
        
        if isinstance(item, dict):
            if item.get("type") == "reply" and "reply" in item:
                item_id = item["reply"].get("id", "")
                item_title = item["reply"].get("title", "")
            else:
                item_id = item.get("id", "")
                item_title = item.get("title", "")
                
        is_slot = False
        item_id_upper = str(item_id).upper()
        item_title_lower = str(item_title).lower()
        
        if any(w in item_id_upper for w in ("SLOT_", "TIME_", "MORNING", "AFTERNOON", "EVENING", "ANYTIME")):
            is_slot = True
        elif any(w in item_title_lower for w in ("morning", "afternoon", "evening", "anytime")):
            is_slot = True
            
        if is_slot:
            if not is_slot_available_today(item_id, item_title):
                print(f"⏰ Hiding lapsed slot: {item_title or item_id} for {phone}")
                continue
                
        filtered.append(item)
    return filtered

def format_custom_renewal_type(text: str) -> str:
    """
    Standardizes a custom renewal string to '<N>th Renewal' if a number is found.
    """
    import re
    clean = text.strip()
    match = re.search(r'\d+', clean)
    if match:
        num = int(match.group(0))
        if 11 <= (num % 100) <= 13:
            suffix = 'th'
        else:
            suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(num % 10, 'th')
        return f"{num}{suffix} Renewal"
    return clean.title()

def validate_and_format_renewal_type(text: str) -> tuple[bool, str, str]:
    """
    Validates and formats a user's custom renewal type input.
    Returns: (is_valid, formatted_value, fallback_message)
    """
    t = text.strip()
    t_lower = t.lower()
    
    # Common words related to renewal
    renewal_words = [
        "renewal", "time", "year", "year's", "st", "nd", "rd", "th", 
        "once", "twice", "first", "second", "third", "fourth", "fifth", 
        "sixth", "seventh", "eighth", "ninth", "tenth", "eleventh", "twelfth"
    ]
    
    # Check if there is a number or standard renewal words
    import re
    num_match = re.search(r'\d+', t)
    
    is_valid_rule = False
    if num_match:
        is_valid_rule = True
        
    if is_valid_rule:
        formatted = format_custom_renewal_type(t)
        return True, formatted, ""
        
    # If rule checks are inconclusive, call the LLM
    prompt = f"""
    You are an AI expert validating a user's input for their vehicle insurance renewal count.
    The user was asked: "Please type your renewal type:" (meaning which number of renewal this is, e.g. 7th, 8th, etc.).
    The user typed: "{text}"
    
    Determine if this input is a valid representation of a renewal count or sequence (e.g. a number, ordinal, or text like "seventh", "7th", "seven", "7 times", "thirty first", "forty fifth").
    If it is valid, extract the renewal count as a standardized string IN NUMERIC FORMAT (e.g. "7th Renewal", "10th Renewal", "31st Renewal", "45th Renewal").
    CRITICAL: Even if the user types the number in words (like "forty fifth renewal"), you MUST convert it to digits (e.g. "45th Renewal"). Never output words for numbers.
    If it is NOT related to a renewal type (e.g. gibberish, name, unrelated text), respond with a professional fallback message asking them to provide a valid renewal number.
    
    Format your response as a JSON object with the following keys:
    - "is_valid": true/false
    - "formatted_value": the standardized renewal string if valid (otherwise empty string)
    - "fallback_message": a professional fallback message if invalid (otherwise empty string)
    
    Example response for valid:
    {{
      "is_valid": true,
      "formatted_value": "45th Renewal",
      "fallback_message": ""
    }}
    
    Example response for invalid:
    {{
      "is_valid": false,
      "formatted_value": "",
      "fallback_message": "I'm sorry, I couldn't understand that. Could you please specify which number of renewal this is? (e.g., 7th Renewal, 8th Renewal, or simply type the number) 📝"
    }}
    """
    
    try:
        from llm_config import smart_llm_call
        response_text = smart_llm_call(
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        import json
        result = json.loads(response_text)
        is_valid = result.get("is_valid", False)
        formatted_val = result.get("formatted_value", "")
        fallback_msg = result.get("fallback_message", "")
        if is_valid and formatted_val:
            return True, formatted_val, ""
        else:
            fallback = fallback_msg or "I'm sorry, I couldn't understand that. Could you please specify which number of renewal this is? (e.g., 7th Renewal, 8th Renewal, or simply type the number) 📝"
            return False, "", fallback
    except Exception as e:
        print(f"[renewal_validator] LLM validation error: {e}")
        return False, "", "I'm sorry, I couldn't understand that. Could you please specify which number of renewal this is? (e.g., 7th Renewal, 8th Renewal, or simply type the number) 📝"


# ============================================================
# CAR BRAND VALIDATOR & CLEANER
# ============================================================

def validate_and_clean_car_brand(text: str) -> tuple[bool, str, str]:
    """
    Validates if the user input represents a valid/meaningful car brand name.
    Returns: (is_valid, clean_brand, fallback_message)
    """
    t = text.strip()
    if not t:
        return False, "", "⚠️ I didn't receive a brand name. Could you please type your car's brand? 🚗"
    
    t_lower = t.lower()
    
    # 1. Repeating characters check (e.g. "sss", "ccc", "aaaa")
    if len(t) > 1 and len(set(t_lower)) == 1:
        return False, "", "⚠️ That doesn't seem to be a valid car brand. Please type the correct brand name (e.g., Hyundai, Maruti, Tata): 🚗"
        
    # 2. Too short or contains special symbols only
    import re
    if len(t) < 2 or not re.match(r"^[A-Za-z0-9\s\-]+$", t):
        return False, "", "⚠️ That doesn't seem to be a valid car brand. Please type the correct brand name (e.g., Hyundai, Maruti, Tata): 🚗"
        
    # 3. Known common greeting/refusal words
    refusal_words = {"no", "yes", "stop", "cancel", "bye", "hi", "hello", "hey", "test", "dummy", "none", "na", "n/a", "ok", "okay", "i don't know", "skip"}
    if t_lower in refusal_words:
        return False, "", "⚠️ Please type a valid car brand (e.g., Hyundai, Maruti, Tata): 🚗"

    messages = [
        {
            "role": "system",
            "content": "You are a professional automotive brand validator for an automotive chatbot. Respond ONLY with a valid JSON object."
        },
        {
            "role": "user",
            "content": f"""Analyze the user input to determine if it represents a valid, real-world automotive manufacturer/brand.
User Input: "{t}"

Rules:
1. is_valid (boolean): True if it is a real automotive brand (e.g. Maruti, Tata, Mahindra, Hyundai, BMW, Toyota, Mercedes, Audi, Ford, Honda, etc.), or if a real brand can be extracted from the text. False if it is gibberish/random letters, digital noise, special symbols (e.g. M%, @brand), placeholder names, or conversational filler with no actual brand.
2. clean_brand (string or null): Properly capitalized brand name. Null if invalid.
3. fallback_message (string or null): A polite, professional fallback message asking for their correct car brand name if invalid. Null if valid.

Return JSON format:
{{"is_valid": true/false, "clean_brand": "extracted_brand" or null, "fallback_message": "message" or null}}"""
        }
    ]
    
    try:
        from llm_config import smart_llm_call
        result = smart_llm_call(
            messages=messages,
            temperature=0.1,
            max_tokens=150,
            response_format={"type": "json_object"},
            as_json=True
        )
        is_valid = result.get("is_valid", False)
        clean_brand = result.get("clean_brand")
        fallback = result.get("fallback_message")
        
        if is_valid and clean_brand:
            return True, clean_brand, ""
        else:
            if not fallback:
                fallback = "⚠️ That doesn't seem to be a valid car brand. Please type the correct brand name (e.g., Hyundai, Maruti, Tata): 🚗"
            return False, "", fallback
    except Exception as e:
        print(f"[brand_validator] LLM validation error: {e}")
        return True, t.title(), ""


# ============================================================
# CAR MODEL VALIDATOR & CLEANER
# ============================================================

def validate_and_clean_car_model(text: str) -> tuple[bool, str, str]:
    """
    Validates if the user input represents a valid/meaningful car model name.
    Returns: (is_valid, clean_model, fallback_message)
    """
    t = text.strip()
    if not t:
        return False, "", "⚠️ I didn't receive a model name. Could you please type your car's model? 🚗"
    
    t_lower = t.lower()
    
    # 1. Repeating characters check
    if len(t) > 1 and len(set(t_lower)) == 1:
        return False, "", "⚠️ That doesn't seem to be a valid car model. Please type the correct model name (e.g., Swift, Creta, Nexon): 🚗"
        
    # 2. Too short or contains special symbols only
    import re
    if len(t) < 2 or not re.match(r"^[A-Za-z0-9\s\-]+$", t):
        return False, "", "⚠️ That doesn't seem to be a valid car model. Please type the correct model name (e.g., Swift, Creta, Nexon): 🚗"
        
    # 3. Known common greeting/refusal words
    refusal_words = {"no", "yes", "stop", "cancel", "bye", "hi", "hello", "hey", "test", "dummy", "none", "na", "n/a", "ok", "okay", "i don't know", "skip"}
    if t_lower in refusal_words:
        return False, "", "⚠️ Please type a valid car model (e.g., Swift, Creta, Nexon): 🚗"

    messages = [
        {
            "role": "system",
            "content": "You are a professional automotive model validator for an automotive chatbot. Respond ONLY with a valid JSON object."
        },
        {
            "role": "user",
            "content": f"""Analyze the user input to determine if it represents a valid, real-world automotive model.
User Input: "{t}"

Rules:
1. is_valid (boolean): True if it is a real automotive model (e.g. Swift, Creta, Nexon, City, Fortuner, Thar, Scorpio, i20, Alto, etc.) or a realistic car model name, or if a realistic car model can be extracted. False if it is gibberish/random letters, digital noise, special symbols (e.g. M%, @model), placeholder names, or conversational filler with no model.
2. clean_model (string or null): Properly capitalized model name. Null if invalid.
3. fallback_message (string or null): A polite, professional fallback message asking for their correct car model name if invalid. Null if valid.

Return JSON format:
{{"is_valid": true/false, "clean_model": "extracted_model" or null, "fallback_message": "message" or null}}"""
        }
    ]
    
    try:
        from llm_config import smart_llm_call
        result = smart_llm_call(
            messages=messages,
            temperature=0.1,
            max_tokens=150,
            response_format={"type": "json_object"},
            as_json=True
        )
        is_valid = result.get("is_valid", False)
        clean_model = result.get("clean_model")
        fallback = result.get("fallback_message")
        
        if is_valid and clean_model:
            return True, clean_model, ""
        else:
            if not fallback:
                fallback = "⚠️ That doesn't seem to be a valid car model. Please type the correct model name (e.g., Swift, Creta, Nexon): 🚗"
            return False, "", fallback
    except Exception as e:
        print(f"[model_validator] LLM validation error: {e}")
        return True, t.title(), ""