# utils.py
# ============================================================
# Shared utility functions used across multiple flow modules.
# Import from here instead of defining locally in each file.
# ============================================================

import uuid
import time
import re
import os
import json
from datetime import datetime, date, timedelta
from dotenv import load_dotenv
from groq import Groq
from config import USER_STATE

load_dotenv()

# Initialize Groq client
_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
_MODEL_NAME = "llama-3.3-70b-versatile"

# ============================================================
# TOKEN MANAGEMENT
# ============================================================

# In-memory token store for upload tokens generated via app.py endpoints.
# Tokens generated by insurance.py are stored inside USER_STATE[phone]["upload_token"].
UPLOAD_TOKENS: dict = {}

TOKEN_EXPIRY_SECONDS = 3600  # 1 hour


def generate_upload_token(phone: str, name: str, vehicle: str) -> str:
    """
    Generate a secure UUID-based upload token and persist it in USER_STATE
    so it can be validated later by get_user_from_token().

    Stores the token under USER_STATE[phone]["upload_token"] which is the
    single source of truth checked by get_user_from_token().
    """
    token = str(uuid.uuid4())

    USER_STATE.setdefault(phone, {})
    USER_STATE[phone]["upload_token"] = {
        "token": token,
        "name": name,
        "vehicle": vehicle,
        "timestamp": time.time(),
        "mobile": phone,   # kept for convenience when retrieved via token scan
    }

    print(f"✅ Generated upload token for {phone}: {token}")
    return token


def get_user_from_token(token: str) -> dict | None:
    """
    Validate a token and return the associated user data dict, or None if the
    token is missing / expired.

    Checks USER_STATE first (tokens created by insurance flow / generate_upload_token),
    then falls back to the legacy UPLOAD_TOKENS dict kept for backward compatibility.

    Returned dict keys: mobile, name, vehicle, timestamp
    """
    # ── 1. Scan USER_STATE (primary store) ──────────────────────────────
    for phone, user_data in USER_STATE.items():
        token_data = user_data.get("upload_token")
        if not token_data:
            continue
        if token_data.get("token") != token:
            continue

        if time.time() - token_data.get("timestamp", 0) > TOKEN_EXPIRY_SECONDS:
            print(f"❌ Token expired in USER_STATE: {token}")
            user_data.pop("upload_token", None)
            return None

        print(f"✅ Valid token from USER_STATE for {phone}")
        return {
            "mobile": phone,
            "name": token_data.get("name", ""),
            "vehicle": token_data.get("vehicle", ""),
            "timestamp": token_data.get("timestamp", 0),
        }

    # ── 2. Fallback: legacy UPLOAD_TOKENS dict ───────────────────────────
    if token in UPLOAD_TOKENS:
        data = UPLOAD_TOKENS[token]
        if time.time() - data.get("timestamp", 0) > TOKEN_EXPIRY_SECONDS:
            print(f"❌ Token expired in UPLOAD_TOKENS: {token}")
            UPLOAD_TOKENS.pop(token, None)
            return None

        print(f"✅ Valid token from UPLOAD_TOKENS for {data['mobile']}")
        return data

    print(f"❌ Token not found: {token}")
    return None


def revoke_upload_token(token: str) -> None:
    """Remove a token from both USER_STATE and UPLOAD_TOKENS after successful upload."""
    # Remove from legacy dict
    UPLOAD_TOKENS.pop(token, None)

    # Remove from USER_STATE
    for phone, user_data in USER_STATE.items():
        token_data = user_data.get("upload_token")
        if token_data and token_data.get("token") == token:
            user_data.pop("upload_token", None)
            print(f"✅ Token revoked from USER_STATE for {phone}")
            break


# ============================================================
# PHONE NUMBER FORMATTING
# ============================================================

def format_mobile(phone: str) -> str:
    """
    Format an Indian mobile number to the +91-XXXXXXXXXX display form.

    Accepted input formats:
        918688977412  →  +91-8688977412
        8688977412    →  +91-8688977412
        Any other     →  returned as-is (safe fallback)
    """
    phone = phone.strip()
    if phone.startswith("91") and len(phone) == 12:
        return f"+91-{phone[2:]}"
    if len(phone) == 10:
        return f"+91-{phone}"
    return phone


def normalize_text(text: str) -> str:
    """Normalize user text for robust keyword matching."""
    t = (text or "").lower()
    corrections = {
        "renwal": "renew",
        "renwe": "renew",
        "renw": "renew",
        "estimtae": "estimate",
        "estmate": "estimate",
        "estimat": "estimate",
        "estimte": "estimate",
        "quate": "quote",
        "quoute": "quote",
        "polciy": "policy",
        "premuim": "premium",
        "prmium": "premium",
    }
    for wrong, right in corrections.items():
        t = t.replace(wrong, right)
    return t.strip()


def classify_insurance_intent_request(text: str) -> str | None:
    """
    Return an explicit insurance flow intent from user text, or None.

    Uses broad keyword + semantic pattern matching so natural language
    requests like "i want to renew my insurance" or "can I get a quote"
    are reliably classified as action intents — not knowledge queries.
    """
    t = normalize_text(text)

    # ── RENEWAL action keywords ──────────────────────────────────────────
    # Covers: explicit requests, natural language, typos, mixed phrasing
    renew_kw = [
        # Direct action phrases
        "renew my", "renew my insurance", "renew insurance", "renew my policy",
        "renew policy", "renewal of my", "renewal for my",
        "want to renew", "want to renew my", "i want to renew",
        "i want renew", "i want my renew", "i want renewal",
        "need to renew", "need renewal", "looking to renew",
        "renew now", "renew today", "renewal request", "request renewal",
        "policy renew", "policy renew karna", "policy lena",
        # New policy / purchase
        "new policy for my", "buy insurance for", "purchase policy",
        "buy a policy", "take insurance", "take a policy",
        "get insurance for my", "apply for insurance",
        "i want insurance", "i need insurance for my",
        # Colloquial / short
        "do renewal", "start renewal", "process renewal",
        "book renewal", "schedule renewal", "renewal", "renew"
    ]

    # ── ESTIMATE action keywords ─────────────────────────────────────────
    # Covers: quote, estimate, premium calculation requests
    estimate_kw = [
        # Direct estimate/quote requests
        "get estimate", "get an estimate", "get a estimate",
        "request estimate", "request a quote", "request quote",
        "need estimate", "need a quote", "need quote",
        "want estimate", "want a quote", "want quote",
        "want an estimate", "i want estimate", "i want a quote",
        "send estimate", "give me estimate", "give me a quote",
        "give estimate", "share estimate", "send quote",
        "estimate", "quote",
        # Premium/price calculation (must be part of an action phrase)
        "calculate premium", "calculate premium for my",
        "how much for my car", "how much for my vehicle",
        "how much will it cost for my", "how much does it cost for my",
        "quote for my car", "quote for my vehicle",
        "estimate for my car", "estimate for my vehicle",
        "premium estimate", "insurance estimate for my",
        "insurance quote for my", "premium for my car",
        "premium for my vehicle", "cost of insurance for my",
        "price of insurance for my",
        # Action-oriented short forms
        "get quote", "get a quote", "get me a quote",
        "get me estimate", "get me an estimate",
        "i need an estimate", "i need a estimate",
        "i need quote", "can i get estimate", "can i get a quote",
        "can you give estimate", "can you give me estimate",
        "can you give quote", "can you give me quote",
    ]

    # ── HISTORY keywords ─────────────────────────────────────────────────
    history_kw = [
        "past policy", "previous policy", "old policy", "my history",
        "last premium", "last policy", "my records", "policy history",
        "insurance history", "show my policies", "my past insurance",
        "my previous insurance",
    ]

    # ── ADVISOR keywords ─────────────────────────────────────────────────
    advisor_kw = [
        "talk to", "speak to", "speak with", "talk with",
        "human", "agent", "advisor", "adviser",
        "customer care", "customer support", "support team",
        "contact advisor", "call me", "call back",
        "connect me", "connect to advisor", "real person",
    ]

    if any(k in t for k in renew_kw):
        return "RENEW_INSURANCE"
    if any(k in t for k in estimate_kw):
        return "GET_ESTIMATE"
    if any(k in t for k in history_kw):
        return "INSURANCE_HISTORY"
    if any(k in t for k in advisor_kw):
        return "TALK_TO_ADVISOR"
    return None


def is_insurance_knowledge_query(text: str) -> bool:
    """
    Return True ONLY for purely informational insurance questions.

    CRITICAL: This must return False for ANY action request — the user
    wanting to renew, get an estimate, etc. must NEVER be classified as
    a knowledge query.  classify_insurance_intent_request() is the
    definitive gatekeeper — if it returns an intent, we are NOT in
    knowledge-query territory.

    IMPORTANT: "what is the premium amount", "how is premium calculated",
    "how much does insurance cost in general" etc. are KNOWLEDGE queries —
    the user is asking for information, NOT requesting a quote for their
    specific vehicle.  These must return True so the AI expert answers them
    and the estimate flow is NOT triggered.
    """
    if not text:
        return False

    t = normalize_text(text)

    # ── PRIORITY 1: Pure knowledge question patterns ─────────────────────
    # Check these BEFORE the action-intent gate so that questions like
    # "what is the premium amount and how is it calculated" are never
    # misrouted to the estimate flow.
    #
    # These phrases unambiguously mean the user wants INFORMATION,
    # not to initiate a quote/estimate for their specific vehicle.
    definitive_knowledge_phrases = [
        # Premium / cost information questions
        "what is the premium", "what is premium", "what is the cost",
        "how is premium calculated", "how is the premium calculated",
        "how is premium", "how premium is calculated",
        "how it is calculated", "how is it calculated",
        "what is the premium amount", "premium amount",
        "how much is the premium", "how is insurance premium",
        "how is insurance cost", "how is insurance calculated",
        "how much does insurance cost", "how much is insurance in general",
        "how is the cost calculated", "how do they calculate",
        "what factors affect premium", "what affects premium",
        "what affects insurance", "factors for premium",
        "what determines premium", "what determines the premium",
        # Coverage / policy knowledge
        "what is comprehensive", "what is third party",
        "what is own damage", "what is od", "what is tp",
        "what is saod", "what does saod mean",
        "what does comprehensive cover", "what does third party cover",
        "what is covered", "what is not covered", "what is excluded",
        "difference between comprehensive", "difference between third party",
        "comprehensive vs third party", "third party vs comprehensive",
        # NCB / IDV / add-ons
        "what is ncb", "what is no claim bonus", "how does ncb work",
        "how ncb works", "how much ncb", "what is idv",
        "what is insured declared value", "how is idv calculated",
        "what is zero depreciation", "what is nil depreciation",
        "what is engine protection", "what is roadside assistance",
        "what is return to invoice", "what is pa cover",
        "what is personal accident", "what are add ons", "what are addons",
        # Claim / process knowledge
        "what is claim process", "how to raise a claim",
        "how to file a claim", "claim process", "claim procedure",
        "how does claim work", "how claims work", "cashless claim",
        "what is reimbursement", "claim settlement",
        # Policy / lapse / renewal knowledge (informational)
        "what happens if policy lapses", "what is grace period",
        "what is policy lapse", "what is break in insurance",
        "what is fresh insurance", "what is renewal", "how does renewal work",
        "what is multi year policy", "what is long term policy",
        # General questions with question words
        "explain insurance", "explain premium", "explain coverage",
        "tell me about insurance", "tell me about premium",
        "describe insurance", "how does insurance work",
        "how does motor insurance work", "how does vehicle insurance work",
        "what is motor insurance", "what is vehicle insurance",
        "what is car insurance",
    ]
    if any(phrase in t for phrase in definitive_knowledge_phrases):
        return True

    # ── PRIORITY 2: Flexible pattern matching for questions ────────────────
    # Catches variations like "how the premium amount is calculated"
    import re as _re
    
    # Informational 'how' questions about premium/cost
    if _re.search(r'\bhow\s+.*\b(premium|cost|price|amount|idv|ncb)\b.*\b(calculated|determined|worked|work|decided|comes)\b', t):
        return True
        
    # 'what is' questions about insurance concepts
    if _re.search(r'\bwhat\s+is\s+.*\b(premium|cost|price|coverage|policy|renewal|ncb|idv|claim|addon|comp|third)\b', t):
        return True

    # 'explain' / 'tell me' patterns
    if _re.search(r'\b(explain|tell me|detail|describe|what is|how does)\b.*\b(insurance|premium|renewal|claim|policy)\b', t):
        return True

    # ── PRIORITY 3: Action-intent check is AUTHORITATIVE ─────────────────
    # If the text resolves to a concrete flow action, it is NOT a
    # knowledge query — even if it also contains question words.
    if classify_insurance_intent_request(text) is not None:
        return False

    # ── Hard-block: explicit action verbs that signal "do something" ─────
    # These phrases indicate the user wants an action, not an explanation.
    action_signals = [
        "i want to", "i want", "i need to", "i need", "i would like to",
        "i'd like to", "please renew", "please give", "please send",
        "please provide", "please get", "please calculate",
        "can you renew", "can you give", "can you send",
        "help me renew", "help me get", "help me with renewal",
        "help me with estimate", "start renewal", "begin renewal",
        "do renewal", "do estimate", "initiate renewal",
    ]
    if any(sig in t for sig in action_signals):
        # Only treat as knowledge if it's clearly a "how do I" question
        # not a "I want to" request.
        how_question = any(q in t for q in [
            "how do i", "how can i", "how to", "what is", "what are",
            "explain", "tell me about", "describe"
        ])
        if not how_question:
            # It's an action request — not a knowledge query
            return False

    # ── Informational patterns — genuine knowledge questions ─────────────
    info_phrases = [
        "what is", "what are", "how is", "how are", "why is", "why are",
        "when is", "when are", "where is", "where are", "which is",
        "explain", "describe", "clarify", "tell me about",
        "difference between", "compare", "meaning of", "definition of",
        "process of", "procedure for", "policy details", "premium amount",
        "idv", "ncb", "comprehensive", "third party", "own damage",
        "zero depreciation", "claim process", "claim amount",
        "what does", "how does", "how do", "how is premium calculated",
        "what is covered", "what is not covered",
    ]
    if any(phrase in t for phrase in info_phrases):
        return True

    # ── Longer question-form sentences ───────────────────────────────────
    question_terms = [
        "what", "how", "why", "when", "where", "which",
        "tell me", "explain", "describe", "difference", "compare",
    ]
    if len(t.split()) >= 5 and any(term in t for term in question_terms):
        return True

    return False


# ============================================================
# DATE FORMATTING
# ============================================================

def format_date_only(dt) -> str:
    """
    Convert a date / datetime / string value from the DB into dd-mm-yyyy.
    Returns "N/A" for None or unparseable inputs.
    """
    if not dt:
        return "N/A"

    if isinstance(dt, date):          # covers both date and datetime
        return dt.strftime("%d-%m-%Y")

    s = str(dt)
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, fmt).strftime("%d-%m-%Y")
        except ValueError:
            continue

    return s  # safe fallback – never crash


# ============================================================
# APPOINTMENT DATE HELPERS
# ============================================================

def get_remaining_week_dates() -> list:
    """
    Return the remaining dates in the *current* week starting from the day after
    tomorrow up to and including the coming Sunday.

    Used by insurance, sales, and used-cars flows for appointment scheduling.
    """
    today = datetime.now().date()
    start_day = today + timedelta(days=2)

    days_until_sunday = 6 - start_day.weekday()   # Monday=0 … Sunday=6
    if days_until_sunday < 0:
        days_until_sunday = 0

    end_day = start_day + timedelta(days=days_until_sunday)

    dates = []
    current = start_day
    while current <= end_day:
        dates.append(current)
        current += timedelta(days=1)

    return dates


def get_next_week_dates() -> list:
    """
    Return all seven days of *next* week (Monday → Sunday).

    Used by insurance, sales, and used-cars flows for appointment scheduling.
    """
    today = datetime.now().date()
    days_until_next_monday = 7 - today.weekday()
    next_monday = today + timedelta(days=days_until_next_monday)

    return [next_monday + timedelta(days=i) for i in range(7)]


# ============================================================
# APPOINTMENT TIME VALIDATION
# ============================================================

from datetime import datetime, date, timedelta

BOOKING_CUTOFF_HOUR = 18  # 6 PM — no same-day bookings after this hour


def get_smart_default_date() -> tuple[date, bool]:
    """
    Returns the smart default booking date based on current time.

    Rule:
      - Before 6 PM  → today is bookable → return (today, False)
      - At/After 6 PM → today is blocked  → return (tomorrow, True)

    Returns:
        (default_date, was_redirected_to_tomorrow)
        was_redirected_to_tomorrow is True when we auto-advanced past today.

    Used by all flows when customer selects "Today" after cutoff — instead of
    rejecting and re-prompting, we silently advance to tomorrow and inform them.
    """
    now = datetime.now()
    today = now.date()
    if now.hour >= BOOKING_CUTOFF_HOUR:
        return today + timedelta(days=1), True
    return today, False


def is_valid_appointment_slot(appointment_date: date, appointment_time_str: str = None) -> tuple[bool, str]:
    """
    Validate whether an appointment date+time is bookable.

    Rules:
      - If current time >= 6 PM, today is blocked entirely.
      - If current time < 6 PM, today is allowed only if the chosen time
        is at least 1 hour from now.
      - Past dates are always blocked.

    Args:
        appointment_date: The date the customer wants to book.
        appointment_time_str: Optional time string like "10:30 AM" or "14:00".

    Returns:
        (True, "") if valid.
        (False, reason_message) if invalid.
    """
    now = datetime.now()
    today = now.date()

    # ── Block past dates ────────────────────────────────────────
    if appointment_date < today:
        return False, "⚠️ That date has already passed. Please choose a future date."

    # ── Same-day logic ──────────────────────────────────────────
    if appointment_date == today:
        if now.hour >= BOOKING_CUTOFF_HOUR:
            return False, (
                f"⚠️ Same-day bookings are not accepted after 6:00 PM.\n"
                f"Please choose a date from tomorrow onwards. 📅"
            )

        # If a specific time was also provided, check it's not too soon
        if appointment_time_str:
            parsed_time = _parse_time(appointment_time_str)
            if parsed_time:
                appointment_dt = datetime.combine(today, parsed_time)
                if appointment_dt <= now + timedelta(hours=1):
                    return False, (
                        f"⚠️ Please book at least 1 hour in advance.\n"
                        f"The earliest available slot today is "
                        f"{(now + timedelta(hours=1)).strftime('%I:%M %p')}. ⏰"
                    )

    return True, ""


def _parse_time(time_str: str):
    """
    Parse a time string into a datetime.time object.
    Supports formats: '10:30 AM', '2:00 PM', '14:00', '9am', etc.
    Returns None if unparseable.
    """
    time_str = time_str.strip()
    for fmt in ("%I:%M %p", "%I:%M%p", "%H:%M", "%I %p", "%I%p"):
        try:
            return datetime.strptime(time_str.upper(), fmt.upper()).time()
        except ValueError:
            continue
    return None


def get_available_booking_dates() -> list:
    """
    Return dates available for booking based on current time.
    
    - Before 6 PM  → today + remaining week + next week
    - After 6 PM   → starts from TOMORROW (today excluded)
    """
    now = datetime.now()
    today = now.date()

    if now.hour >= BOOKING_CUTOFF_HOUR:
        # Push start to tomorrow
        start_day = today + timedelta(days=1)
    else:
        start_day = today

    # Build remaining current week from start_day
    days_until_sunday = 6 - start_day.weekday()
    end_of_week = start_day + timedelta(days=max(days_until_sunday, 0))

    dates = []
    current = start_day
    while current <= end_of_week:
        dates.append(current)
        current += timedelta(days=1)

    return dates


# ============================================================
# AI QUERY GATE  —  is_genuine_query()
# ============================================================
# This is the single source of truth for ALL flows.
#
# PURPOSE:
#   Determine whether a user's free-text input is a genuine
#   question/query that should be answered by the AI, OR just
#   a flow input (reg number, name, date, address, etc.) that
#   the flow itself should handle with a re-prompt.
#
# RULE:
#   AI responds ONLY when the user is genuinely asking a question.
#   For everything else (form inputs, accidental text, short
#   words that look like menu selections) the flow re-prompts.
#
# STATES WHERE AI IS NEVER CALLED:
#   - Any state that expects a structured input:
#       vehicle reg number, name, address, date, time slot,
#       phone number, car brand/model/year, city, loan amount.
#   These states should handle bad input with a polite re-prompt,
#   NOT by routing to the AI.
# ============================================================

# States in each flow that expect raw user text input (NOT questions).
# AI should NEVER be triggered in these states regardless of what the user types.
_STRUCTURED_INPUT_STATES = {
    # Insurance — vehicle lookup and estimate
    "INSURANCE_LOOKUP",             # expects vehicle reg number
    # NOTE: INSURANCE_ESTIMATE_NAME and STATE_4_NAME are NOT listed here.
    # They use _handle_mid_flow_knowledge_query() to intercept knowledge questions
    # BEFORE form validation, then re-prompt the form field after answering.
    # Listing them here would prevent knowledge queries from reaching the AI.
    "INSURANCE_ESTIMATE_LINK_SENT", # link sent, waiting for upload or buttons
    # NOTE: STATE_4_ADDRESS is NOT listed here — the interceptor handles it too.
    # NOTE: STATE_4_RENEW_TYPE, STATE_4_MODE, STATE_4_DATE, STATE_4_LATER_WEEK,
    # STATE_4_NEXT_WEEK, STATE_4_SLOT, STATE_4_DONE are intentionally NOT listed here.
    # Those states have their own inline keyword resolvers that run first.
    # When the resolver can't match the input (e.g. a genuine question),
    # the flow calls _route_via_ai() which needs is_genuine_query() to return True.
    "STATE_5_ADVISOR",              # advisor handoff
    "INSURANCE_AGENT_CONFIRMATION", # human agent confirmation
    "INSURANCE_VEHICLE_FOUND",      # after lookup, list/menu state

    # Sales — car selection and customer collection
    "SALES_COLLECT_NAME",           # expects customer name
    "SALES_COLLECT_PHONE",          # expects phone number
    "SALES_COLLECT_ADDRESS",        # expects address (home visit)
    "SALES_AGENT_CONFIRMATION",     # human agent confirmation

    # Refinancing — customer collection and loan details
    "REFINANCING_ASK_NAME",         # expects name
    "REFINANCING_ASK_PHONE",        # expects phone
    "REFINANCING_ASK_CITY",         # expects city
    "REFINANCING_ASK_BRAND_OTHER",  # expects brand name
    "REFINANCING_ASK_MODEL",        # expects model name
    "REFINANCING_ASK_YEAR",         # expects year
    "REFINANCING_ASK_HAS_LOAN",    # loan status selection
    "REFINANCING_ASK_REMAINING_AMT",# remaining loan amount
    "REFINANCING_ASK_LOAN_NEEDED", # required loan amount
    "REFINANCING_ASK_CONTACT_TIME", # preferred contact time
    "REFINANCING_AGENT_CONFIRMATION", # human agent confirmation

    # Insurance: name/age collection states (prevent AI interference)
    "STATE_4_WAITING_NAME",
    "STATE_4_WAITING_AGE",
    "STATE_5_WAITING_NAME",
    "STATE_5_WAITING_AGE",

    # Used Cars: name/data collection
    "USED_VALUATION_COLLECT_NAME",
    "USED_VALUATION_COLLECT_PHONE",
    "USED_VALUATION_COLLECT_LOCATION",
    "USED_BOOK_COLLECT_NAME",
    "USED_BOOK_COLLECT_LOCATION",
    "USED_BOOK_COLLECT_LICENSE",
    "USED_CALLBACK_COLLECT_NAME",
    "USED_CALLBACK_COLLECT_PHONE",
    "USED_CALLBACK_COLLECT_NEED",
    "EXCH_COLLECT_NAME",
    "EXCH_COLLECT_CITY",
    "EXCH_FINANCE_CALLBACK",
    "EXCH_TD_ADDRESS",

    # Service: name/address collection (prevent AI interference)
    "waiting_full_name",
    "waiting_phone_number",
    "waiting_pickup_address",
    "waiting_drop_address_input",
    "waiting_special_instructions",
    "waiting_city_input",
    "waiting_vehicle_model_input",
    "waiting_odo_reading_input",
    "SERVICE_COLLECT_NAME",
    "SERVICE_COLLECT_PHONE",
    "SERVICE_COLLECT_ADDRESS",
    "SERVICE_LOOKUP",               # service: expects vehicle reg number
    "SERVICE_SELECT_SERVICE_TYPE",  # service type selection
    "SERVICE_AGENT_CONFIRMATION",   # human agent confirmation
}

# States that match input-style flows by prefix.
_STRUCTURED_INPUT_STATE_PREFIXES = {
    # NOTE: Flow-specific prefixes like 'SERVICE_', 'USED_', 'SALES_', 'REFINANCING_' 
    # are INTENTIONALLY REMOVED from here to allow is_genuine_query()
    # to check the actual text for questions mid-flow.
}

# Question/query indicator words and patterns.
_QUESTION_WORDS = {
    "what", "which", "who", "when", "where", "why", "how",
    "is", "are", "was", "were", "will", "would", "can", "could",
    "do", "does", "did", "should", "has", "have", "had",
    "tell me", "explain", "describe", "clarify", "difference",
    "compare", "versus", "vs", "meaning", "definition",
    "help", "assist", "support", "information", "info",
    "know", "understand", "find out", "find", "show me",
    "calculate", "estimate", "quote", "cost", "price", "rate",
    "available", "offer", "provide", "include", "cover",
    "benefit", "feature", "advantage", "work", "happen",
    "process", "procedure", "step", "guide", "recommend",
    "issue", "problem", "fault", "noise", "leak", "light", "warning",
    "vibration", "smell", "smoke", "repair", "fix", "check", "service",
    "appointment", "booking", "advisor", "agent", "human", "person",
}

# Minimum word count for a message to be considered a query.
_MIN_QUERY_WORDS = 2


def is_genuine_query(text: str, state: str = "") -> bool:
    """
    Returns True ONLY if the user's text is a genuine question or query
    that should be answered by the AI assistant.

    Returns False for:
      - Vehicle registration numbers (e.g. KA01AB1234)
      - Short inputs (1–2 words) that look like form inputs
      - Pure numbers or alphanumeric codes
      - States that always expect structured form inputs
      - Greetings that should restart the flow, not trigger AI

    Args:
        text  : The raw user message text.
        state : The current flow state (used to block AI in form states).

    Returns:
        bool — True = let AI respond, False = flow handles it.
    """
    if not text:
        return False

    t = text.strip()
    t_lower = t.lower()
    words = t_lower.split()
    word_count = len(words)

    # ── 1. Block AI entirely in structured-input states ─────────────────
    if state in _STRUCTURED_INPUT_STATES or any(str(state).startswith(prefix) for prefix in _STRUCTURED_INPUT_STATE_PREFIXES):
        print(f"[query_gate] BLOCK — structured input state: {state}")
        return False

    # ── 1b. Explicit Intent Check ───────────────────────────────────────
    # If the text matches a known insurance intent (Renew, Estimate, etc.),
    # allow it through so the AI router can execute the flow switch.
    if classify_insurance_intent_request(text):
        print(f"[query_gate] ALLOW — explicit insurance intent: '{t}'")
        return True

    # ── 2. Vehicle registration number pattern ───────────────────────────
    #    Format: 2 letters + 2 digits + optional 2 letters + 4 digits
    #    e.g. KA01AB1234, KL21W2285, MH12DE1433
    if re.match(r'^[A-Za-z]{2}\d{2}[A-Za-z]{0,3}\d{4}$', t.replace(' ', '')):
        print(f"[query_gate] BLOCK — looks like vehicle reg: '{t}'")
        return False

    # ── 3. Pure number or very short code ───────────────────────────────
    if re.match(r'^\d+$', t):
        print(f"[query_gate] BLOCK — pure number: '{t}'")
        return False

    # ── 4. Single word that's just an alphanumeric code ─────────────────
    if word_count == 1 and re.match(r'^[A-Za-z0-9_]{1,20}$', t):
        # Single short words could be menu IDs, codes, names.
        # Exception: if it's a known question word, let it through.
        if t_lower not in _QUESTION_WORDS:
            print(f"[query_gate] BLOCK — single non-question word: '{t}'")
            return False

    # ── 5. Too short to be a real question (1–2 words, no question mark) ─
    if word_count < _MIN_QUERY_WORDS and '?' not in t:
        # Allow known question words even if short (e.g. "how?", "why?")
        if not any(w in _QUESTION_WORDS for w in words):
            print(f"[query_gate] BLOCK — too short, no question mark: '{t}'")
            return False

    # ── 6. Explicit question mark → definitely a query ──────────────────
    if '?' in t:
        print(f"[query_gate] ALLOW — has question mark: '{t}'")
        return True

    # ── 7. Starts with or contains a question word ───────────────────────
    if words and words[0] in _QUESTION_WORDS:
        print(f"[query_gate] ALLOW — starts with question word: '{t}'")
        return True

    if any(qw in t_lower for qw in ["tell me", "explain", "describe", "clarify",
                                      "show me", "find out", "help me", "i want to know",
                                      "what is", "what are", "how much", "how many",
                                      "how does", "how do", "can you", "could you",
                                      "i need help", "please explain", "please tell",
                                      "documents", "what docs", "renewal", "requirements",
                                      "how to renew", "procedure", "process"]):
        print(f"[query_gate] ALLOW — contains query phrase: '{t}'")
        return True

    # ── 8. Longer sentences that look like natural language queries ───────
    #    If 5+ words and NOT just a list of proper nouns or numbers,
    #    it's probably a question even without a question word.
    if word_count >= 5:
        # Check it's not just a sequence of names/codes
        non_alpha = sum(1 for w in words if not re.match(r'^[A-Za-z]+$', w))
        if non_alpha <= 1:  # mostly letters = natural language
            print(f"[query_gate] ALLOW — long natural language sentence: '{t}'")
            return True

    print(f"[query_gate] BLOCK — not identified as a genuine query: '{t}'")
    return False


# ============================================================
# SMART DATE RESOLVER
# Maps natural language dates to IDs (e.g. '24th' -> 'DATE_20240424')
# ============================================================

def resolve_date_from_text(text: str, available_dates: list, prefix: str) -> str | None:
    """
    Intelligently match user's free-text date input to one of the available_dates.
    Uses multiple strategies: ordinal matching, month matching, weekday matching, and AI fallback.
    Handles dates like "4th may", "5 may", "may 5", "24", "Monday", "tomorrow", etc.
    """
    if not text or not available_dates:
        return None
    
    t = text.lower().strip()
    print(f"📅 [utils] resolve_date_from_text: '{text}' (normalized: '{t}')")
    
    # ── Remove ordinal suffixes (st, nd, rd, th) ──────────────────────────
    t_clean = re.sub(r'(st|nd|rd|th)\b', '', t)
    print(f"   Cleaned ordinals: '{t_clean}'")
    
    # Extract all numbers and find the first valid day number
    nums = re.findall(r'\d+', t_clean)
    day_num = None
    if nums:
        day_num = int(nums[0])
        if 1 <= day_num <= 31:
            print(f"   Extracted day number: {day_num}")
        else:
            day_num = None
    
    # ── Month name mapping (full and abbreviated) ─────────────────────────
    month_map = {
        # Full month names
        "january": 1, "february": 2, "march": 3, "april": 4, "may": 5, "june": 6,
        "july": 7, "august": 8, "september": 9, "october": 10, "november": 11, "december": 12,
        # Abbreviated month names
        "jan": 1, "feb": 2, "mar": 3, "apr": 4, "jun": 6,
        "jul": 7, "aug": 8, "sep": 9, "sept": 9, "oct": 10, "nov": 11, "dec": 12,
        # Hindi months
        "january": 1, "phbruary": 2, "march": 3, "april": 4, "may": 5,
    }
    
    month_num = None
    for mname, mnum in month_map.items():
        if mname in t_clean:
            month_num = mnum
            print(f"   Extracted month: {mname} → {mnum}")
            break
    
    # ── Strategy 1: Day + Month (e.g. "4th may", "5 april") ──────────────
    if day_num and month_num:
        print(f"   Trying day+month match: day={day_num}, month={month_num}")
        for d in available_dates:
            if d.day == day_num and d.month == month_num:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ Day+month match found: {d.strftime('%Y-%m-%d')} → {result}")
                return result
        print(f"   ❌ No date found for {day_num}/{month_num}")
    
    # ── Strategy 2: Day only (e.g. "24", "5") - if text is very short ───
    if day_num and len(t) <= 5:
        print(f"   Trying day-only match: day={day_num}")
        for d in available_dates:
            if d.day == day_num:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ Day-only match found: {d.strftime('%Y-%m-%d')} → {result}")
                return result
    
    # ── Strategy 3: Weekday name (e.g. "Monday", "Wed", "Friday") ────────
    weekday_map = {
        "monday": 0, "mon": 0, "tuesday": 1, "tue": 1, "wednesday": 2, "wed": 2,
        "thursday": 3, "thu": 3, "friday": 4, "fri": 4, "saturday": 5, "sat": 5,
        "sunday": 6, "sun": 6
    }
    for wday_name, wday_idx in weekday_map.items():
        if wday_name in t_clean:
            print(f"   Trying weekday match: {wday_name} (index={wday_idx})")
            for d in available_dates:
                if d.weekday() == wday_idx:
                    result = f"{prefix}{d.strftime('%Y%m%d')}"
                    print(f"   ✅ Weekday match found: {d.strftime('%Y-%m-%d')} → {result}")
                    return result
            break
    
    # ── Strategy 4: Relative dates ──────────────────────────────────────
    today = date.today()
    if "today" in t_clean or "this day" in t_clean:
        for d in available_dates:
            if d == today:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ 'Today' match: {d.strftime('%Y-%m-%d')} → {result}")
                return result
    
    if "tomorrow" in t_clean or "next day" in t_clean:
        tomorrow = today + timedelta(days=1)
        for d in available_dates:
            if d == tomorrow:
                result = f"{prefix}{d.strftime('%Y%m%d')}"
                print(f"   ✅ 'Tomorrow' match: {d.strftime('%Y-%m-%d')} → {result}")
                return result
    
    # ── Strategy 5: Groq AI fallback for complex/multilingual inputs ─────
    if len(available_dates) > 0:
        try:
            dates_list = "\n".join(
                [f"- {d.strftime('%A')}, {d.strftime('%d %B %Y')} (ID: {prefix}{d.strftime('%Y%m%d')})"
                 for d in sorted(available_dates)]
            )
            
            prompt = f"""Match the user's date input to ONE exact date from the list below.
The date might be in English, Hindi, Tamil, Telugu, or any language.
Extract the specific date they mentioned and find the closest match.

AVAILABLE DATES:
{dates_list}

USER MESSAGE: "{text}"

RULES:
1. If they mention a specific day/month/date, find EXACTLY that date
2. If ambiguous (e.g., "24"), choose the next occurrence of day 24
3. If they say "today", "tomorrow", "Monday", match to that day
4. Return ONLY valid JSON: {{"matched_id": "<full ID from list>", "reason": "<short reason>"}}
5. If NO match possible, return {{"matched_id": "NONE", "reason": "no match found"}}"""

            response = _client.chat.completions.create(
                model=_MODEL_NAME,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=100,
                response_format={"type": "json_object"}
            )
            
            result = json.loads(response.choices[0].message.content.strip())
            matched_id = result.get("matched_id", "NONE")
            reason = result.get("reason", "")
            
            print(f"🤖 [utils] AI fallback: '{text}' → '{matched_id}' (reason: {reason})")
            
            if matched_id and matched_id != "NONE" and matched_id.startswith(prefix):
                return matched_id
            
        except Exception as e:
            print(f"❌ [utils] AI fallback error: {e}")
    
    print(f"   ❌ No match found for: '{text}'")
    return None


# ============================================================
# INTELLIGENT FLOW-AWARE QUERY COMPREHENSION
# Understands customer queries BEFORE rigidly following flow
# ============================================================
def understand_customer_in_flow_context(phone: str, user_text: str, current_state: str, 
                                        flow_context: dict = None) -> dict:
    """
    Use LLM to intelligently understand what customer is really asking/doing,
    even within a predefined flow state.
    
    This MUST be called FIRST in flow handlers to determine if:
    1. Customer is answering the flow question normally → return action="CONTINUE_FLOW"
    2. Customer is asking a question → return action="ANSWER_QUERY" + answer
    3. Customer wants to switch flows/go back → return action="SWITCH_CONTEXT" + action
    4. Customer needs clarification → return action="CLARIFY"
    5. Customer input is ambiguous → return action="AMBIGUOUS"
    
    Returns dict with keys:
    - action: one of ["CONTINUE_FLOW", "ANSWER_QUERY", "SWITCH_CONTEXT", "CLARIFY", "AMBIGUOUS"]
    - should_proceed_with_flow: bool (True if flow should continue normally)
    - response: str (AI's response if action is not CONTINUE_FLOW)
    - extracted_data: dict (normalized/extracted data if extractable)
    - flow_action: str (specific action like "BACK", "MAIN_MENU", "CHANGE_CRITERIA", etc.)
    """
    try:
        if not user_text or not user_text.strip():
            return {
                "action": "AMBIGUOUS",
                "should_proceed_with_flow": False,
                "response": "I didn't catch that. Could you please say that again?",
                "extracted_data": {},
                "flow_action": None
            }
        
        flow_context = flow_context or {}
        
        system_prompt = f"""You are an intelligent flow assistant for an automotive chatbot.
Your job is to understand what the customer REALLY wants, even when they're in the middle of a form/flow.

CURRENT FLOW STATE: {current_state}
FLOW CONTEXT: {json.dumps(flow_context, indent=2)}

Analyze the customer's message and determine:
1. Are they answering the current question normally? (e.g., flow expects "Brand" and they say "Hyundai")
2. Are they asking a question about the product/service?
3. Do they want to go back/switch flows/cancel?
4. Are they expressing concerns or needs that aren't aligned with the current step?
5. Is it ambiguous what they want?

Return ONLY valid JSON with this structure:
{{
    "action": "<CONTINUE_FLOW|ANSWER_QUERY|SWITCH_CONTEXT|CLARIFY|AMBIGUOUS>",
    "confidence": <0.0-1.0>,
    "should_proceed_with_flow": <true|false>,
    "response": "<Your intelligent response to customer>",
    "extracted_data": {{"key": "value"}},
    "flow_action": "<specific action like BACK, MAIN_MENU, CHANGE_CRITERIA, TALK_TO_ADVISOR, or null>"
}}

Guidelines:
- If they clearly answer the question, use CONTINUE_FLOW
- If they ask "what is...", "how does...", "tell me about...", use ANSWER_QUERY
- If they say "go back", "main menu", "talk to someone", use SWITCH_CONTEXT with flow_action
- If they express doubt/concern, use CLARIFY or ANSWER_QUERY
- If unclear, use AMBIGUOUS
- Always be helpful and conversational
- Acknowledge their concern before continuing the flow
"""

        user_prompt = f'Customer message: "{user_text}"'

        response = _client.chat.completions.create(
            model=_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3,
            max_tokens=500,
            response_format={"type": "json_object"}
        )
        
        result = json.loads(response.choices[0].message.content.strip())
        
        print(f"🧠 [Flow Context Understanding] State={current_state}")
        print(f"   Action: {result.get('action')}")
        print(f"   Confidence: {result.get('confidence')}")
        print(f"   Flow Action: {result.get('flow_action')}")
        
        return result
        
    except Exception as e:
        print(f"❌ Flow context understanding error: {e}")
        # Fallback: assume they're trying to continue the flow
        return {
            "action": "CONTINUE_FLOW",
            "should_proceed_with_flow": True,
            "response": None,
            "extracted_data": {},
            "flow_action": None,
            "confidence": 0.5
        }